### ISSUE TITLE
Regenerating world removes highlights

### ISSUE THREAD

**Issue by tecc** [toolbox4minecraft/amidst#832] opened 2020-07-30 16:48 UTC
The title says it all, mostly.
When I regenerate a world (more specifically, random world) the highlights I've set are cleared.
I'd rather have them kept.

**Comment by burgerguy** [comment] 2020-07-31 18:06
Fixed in #830, just hasn't been pulled yet.

**Comment by tecc** [comment] 2020-08-02 11:16
Aha.
That's good.

**Comment by moulins** [comment] 2020-08-20 22:51
Duplicate of #824, closing.

**Closed by moulins** 2020-08-20 22:51 UTC
Labels: duplicate
