### ISSUE TITLE
Online only ????

### ISSUE THREAD

**Issue by RegTuttle** [toolbox4minecraft/amidst#314] opened 2017-04-28 23:36 UTC
Why does the latest versions of amidst need to have an internet connection???
I usually play minecraft when living and working on remote sites around the world. So most of the time I am offline.
Without an internat connection, Amidst crashes.
I understand that you want to search for updates etc. , but please put in an option to work offline as is available with Minecraft and earlier versions of Amidst.

**Comment by stefandollase** [comment] 2017-04-28 23:47
Amidst is able to work offline. If it crashes without an internet connection, this is a bug. Please post the crash report, so we can fix it.

**Comment by RegTuttle** [comment] 2017-04-29 22:52
The crash has now stopped, I have started using the 4.2 version. BUT the application will not find the minecraft profile if I am offline, but no problem when online.

Screenshot attached of the startup window.

 

Regards

 

RegTuttle

**Comment by stefandollase** [comment] 2017-04-29 23:18
Thanks for providing the screenshot. Unfortunately, the screenshot did not make it from your mail to the issue tracker. Thus, I cannot see it. Please post the screenshot directly via the website.

**Comment by stefandollase** [comment] 2017-05-14 19:01
I am closing this issue since it cannot be reproduced and the OP seems to have lost interest.

**Closed by stefandollase** 2017-05-14 19:01 UTC
