### ISSUE TITLE
Amidst 4-6 doesn't like Danish characters

### ISSUE THREAD

**Issue by FarmandSMC** [toolbox4minecraft/amidst#957] opened 2021-04-17 17:37 UTC
[info] Amidst v4.6
[info] Current system time: 2021-04-17 19:23:19.489
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_281'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: 'C:\Users\sschm\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-4,1,main]

**[crash] java.nio.file.InvalidPathException: Illegal char <?> at index 10: C:/Users\S??ren\AppData\Roaming\.minecraft\FarmandsFilmer**

The illegal char should be the Danish letter "ø"

	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createProfileDirectory(DotMinecraftDirectoryService.java:116)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidProfileDirectory(DotMinecraftDirectoryService.java:103)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:57)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:97)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'forge'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:154)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:59)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:97)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[info] There are no updates available.
[info] Successfully loaded remote version list.
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-5,1,main]
[crash] java.nio.file.InvalidPathException: Illegal char <?> at index 10: C:/Users\S??ren\AppData\Roaming\.minecraft\FarmandsFilmer
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createProfileDirectory(DotMinecraftDirectoryService.java:116)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidProfileDirectory(DotMinecraftDirectoryService.java:103)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:57)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:97)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by moulins** [comment] 2021-05-14 16:25
Looks like a duplicate of #936.

**Closed by moulins** 2021-05-14 16:25 UTC
Labels: bug
