### ISSUE TITLE
Amidst 4.3 Beta 2 and Java 64bit on Win 10 Pro

### ISSUE THREAD

**Issue by Dracconis** [toolbox4minecraft/amidst#340] opened 2017-07-30 13:40 UTC
[hs_err_pid5072.log.txt](https://github.com/toolbox4minecraft/amidst/files/1185704/hs_err_pid5072.log.txt)
This happens every time I try to launch the program. If you have Java 32 bit it works fine but not with the 64 bit version of Java jre-8u131-windows-x64 amd up. Minecraft version doesn't matter as the program never loads up. If you have the task manager open at the time of trying to launch Amidst you can see the java binary se launch and immediately close producing the resulting error log file I have attached. This happens with any version of Amidst v 4.2 and up.

**Comment by BigAlanM** [comment] 2017-07-30 13:56
You've got something set up wrong on your computer.
I've been running Amidst constantly for years on whatever version of Java was current at the time.
Right now, today, I'm running it on a Windows 10 64bit system with 64 bit Java 1.8.0_141-b15.
Make sure that Amidst is setup to run with admin privileges on Win 10 (why? I'm not sure, but it helps.)

**Comment by stefandollase** [comment] 2017-07-30 14:15
I cannot say that I know what is wrong, but you might want to have a look at the paths under *Internal exceptions*, e.g.

> C:\re\workspace\8-2-build-windows-amd64-**cygwin**\jdk8u144\9417\hotspot\src\share\vm\prims\jni.cpp

To me, it seems like you are trying to run Amidst with a Java runtime that was installed in a cygwin environment. Is this intended?

Anyway, I close this as invalid, because (as @BigAlanM said) it clearly seems to be an issue on your site.

**Closed by stefandollase** 2017-07-30 14:15 UTC
Labels: bug, invalid

**Comment by Dracconis** [comment] 2017-07-30 14:45
First this is not the first time I have used Amidst. Secondly all I have ever done is installed the current java 64 bit at the time and upgraded it as needed which is now the 1.8.0_144-b01 version. Thirdly running it with and without Admin privileges has no affect on if it will run or not. Fourthly this is a clean fresh install of Win 10 Pro so I know there is nothing setup on my computer wrong as you have stated @BigAlanM 

@stefandollase There is no re folder on my computer so that is not the problem.

**Comment by MattSturgeon** [comment] 2017-07-30 15:48
> This is considered in the business world VERY POOR CUSTOMER SERVICE!

AMIDST is a community driven, non-profit, open source project. It has no obligation to provide customer service, let alone _good_ customer service. It doesn't even have _customers_ (or staff)!

Complaining that hobbyist software developers volunteering their own free time to look at the issue you reported are not attentive enough for your liking is frankly rude and entitled.

Secondly, this is not a support forum. It is a place for tracking bugs and enhancements in the software.

Thirdly, closing an issue based on a presumption is fine. If new information comes up it can easily be re-opened. Closed is not the same as deleted.

----

All that said, @stefandollase still gave you some hints based on the log you provided. He suggested checking whether or not you intended to use a Java installed in cygwin or not:



> > C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u144\9417\hotspot\src\share\vm\prims\jni.cpp
>
> To me, it seems like you are trying to run Amidst with a Java runtime that was installed in a cygwin environment. Is this intended?

From your response, I think you said that directory doesn't exist on your system. That would imply that you are trying to run java from a location that doesn't exist, however the log is telling a different story. `C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u144` is referenced 10 times by java internal exceptions.

**Comment by Dracconis** [comment] 2017-07-30 16:24
No that is not implying that I AM, it is stating that JAVA is trying to. As I stated previously I just download Java from its own website and let it install to its default directory. The fact that when I run Amidst with Java 64 and the log file says it is trying to call from that location has nothing to do with anything I have done. Fresh install of both Win10 Pro and both Java 32 and 64 bit no special changes or other altering software and yet Amidst won't run unless I only use the 32 bit Java with Java 64 bit uninstalled.

@MattSturgeon And just how would you feel if you are reporting a problem and someone told you that you are wrong without taking a good look at the problem or potentially what could be causing the problem aside from a log file and just pointing 1 snip of it and asking you if this was intended and then closing the issue without waiting for your reply? I am sure that you would be in my same position. As for saying that they are hobbyist software developers is a little presumptuous. I would assume that they most likely have jobs working with software all the time and do volunteer the spare free time, in this case, to help out the minecraft community. As for the comment that you quoted from I was stating that it is considered poor customer service, but did not state that this was a business. And yes if people are to continue using their product, which is exactly what this is, then yes they are providing customer service, business or not. Not to mention if you were to go to ANY other product's (whether it be optifine, forge, or mod which is the same as Amidst) website with a problem, you would indeed get actual support help from the creator and its team and not get what appears to be a brush off before the issue has been closed. So no I am not being rude or being entitled when I made the statement that I made.

**Comment by stefandollase** [comment] 2017-07-30 17:08
@Dracconis
I don't think this is leading anywhere. I agree with everything @MattSturgeon said. We provided as much help as we were able to, based on the given information. I did not see any hint that your issue is specific to Amidst, so I closed it. If you are able to provide further information, please do so and I am happy to reopen and further investigate the issue. If there is actually an issue with Amidst, I would like to fix it, but again, from the information you provided there is no reason to think the issue is specific to Amidst.

Next, if you want to get an impression about how we normally handle issues that seem to be related to Amidst, please have a look at the issue tracker. Afterwards, you can actually decide about the, as you say, customer service. I think it is, as you say, a little presumptuous to complain about something that you don't actually know about.

Also, I don't think we need to have the whole *you as a volunteer software developer have to implement my feature and fix my issue now* discussion again. If you would like to have it, please search the issue tracker and you will find it. However, I will say that there is no difference whether or not the maintainer of an open source project is also a software developer in their daily job. The point is, that it takes time and effort to maintain an open source software project and that is the same in both cases. Also, this project makes no money, not even from ads or donations, so don't even think about bringing this argument.

Finally, I would like to invite you to spend your time trying to solve your problem instead of yelling at unrelated people. Also, the offer still stands: If you come back with information that strongly suggest that the issue is actually related to Amidst, we will try our best to solve it. However, if you reply to continue the argument, I will have to look this conversation.

One more thing: If the issue would actually be related to Amidst, we would see much more similar reports about it.

**Comment by stefandollase** [comment] 2017-07-30 17:36
As a side note, to help fixing your issue: If you Google

> thrown at C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u144\9417\hotspot\

which is the part of the crash report that I hinted you at, you only get a few hits from within the last few hours. They belong to crash reports that are similar to yours, but are totally unrelated to Amidst. My wild guess is, that there is an issue with the current Java release and that the path is actually a path on the build server that produces the Java releases.

**Comment by Dracconis** [comment] 2017-07-30 17:37
When I brought this issue to you by no means did I say that the problem was with Amidst in my original statement, but that I had a problem with running it with the 64 bit version of Java. All I was looking for was a very simple answer of yes it has to do with Amidst and we are looking into the issue or there is something wrong with the 64 bit java environment. Instead of getting that kind of answer I am told that I did something wrong to my computer. @stefandollase You however, and I apologize if it seemed as though I attacked you in this thread, did ask if I was trying to run it as intended with your question. So if I have not answered that question clearly enough in my previous statements then here is my answer to your question. No that is not how I intended to run it and I did not install or use any kind of cygwin installer or program to install Java. I just used the normal installers from the Java website for both the 32 and 64 bit versions of the most recent versions of their software. I have suspected that the problem was with the 64 bit Java, but brought the issue here first to see if maybe it was an Amidst related issue and then be pointed in the right direction. My retaliating attacks, if that is what you would like to call them, were because of how my issue was treated based on previous experience with other minecraft software developers.

**Comment by Dracconis** [comment] 2017-07-30 17:42
@stefandollase You most likely can then disregard my previous statement as I did not know you made a secondary post as I was typing my last one. Thank you for that piece of information. I was actually trying to find any related information, using google search of course, to see why I did not have a RE folder or if that was something to do with Java itself when I noticed I had a new email reply from you. So thank you again and I do appreciate the candid replies you gave. Once again as I said if it feels as though I attacked you, if that is what you want to call it, I apologize. This has been frustrating me for sometime and am only getting around to bringing it to your attention to see if you might have been able to shed some light on the issue.

**Comment by Dracconis** [comment] 2017-07-30 20:39
@stefandollase Apparently it has something to do with the 64 bit for sure. I just reinstalled it and for whatever reason amidst works with it now. I have made no adjustments to my computer other than reinstall Java 64 bit.

**Comment by stefandollase** [comment] 2017-07-30 21:00
Thanks for posting the solution of the problem! I am happy to hear that it works for you again.

**Comment by Dracconis** [comment] 2017-08-06 16:02
It seems the problem was not caused by Java 32 or 64 bit but by RivaTuner. After doing a lengthy search starting with "thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\" I found an article which was similar to my problem but not exact, as it had to do with an online game, but stated that I should have been looking for related articles to this part of the error log "#Problematic frame: # C  [d3d9.dll+0xfd0c]". In doing so, I found that the real problem had nothing to do directly with Java, Minecraft, or amidst, but with RivaTuner being installed and how it affects the Java Pipeline. Once again, I would like to apologize to all those here for my actions and behavior and wanted to relay the info I found in case anyone else brings this to your attention in the future or if in helping someone else that they happen to have RT installed also.

As far as I am concerned this can be officially closed. @stefandollase Thank you again for pointing me in the right direction.

**Comment by stefandollase** [comment] 2017-08-06 20:54
Thanks again for letting us know the actual cause of the problem. This is not a given. Also, don't worry about your previous actions and behaviour anymore. You have compensated them by now. I am glad that the issue is resolved. Have a nice day :-)
