### ISSUE TITLE
Request: Export structure locations

### ISSUE THREAD

**Issue by marens101** [toolbox4minecraft/amidst#699] opened 2020-02-15 02:11 UTC
Hi,

It would be amazing to have the ability to export certain structures somehow.
I'm aware of #494, however I can see how that would also be fairly impractical to export an entire world's structures. I was thinking it would also be nice to set a radius to export.

Also, it would be great to be able to export strongholds. They're already loaded up when you go to World -> Go to Stronghold, so even just the ability to save the presented list to a file would be great.

**Comment by burgerguy** [comment] 2020-02-20 02:23
Probably shouldn't be too hard to implement, but it'd be kinda slow if it was also rendering it in another window. You could always use [StructureFinder](https://github.com/burgerguy/StructureFinder), which uses amidst.

**Comment by moulins** [comment] 2020-02-20 18:15
I'll close this as a duplicate of #494, because it is very similar, but I do think this would be nice to have implemented.

(I think the best way would be to have a **Export structures..** action, where you can choose which structures to export and specify a radius)

**Closed by moulins** 2020-02-20 18:15 UTC
Labels: duplicate
