### ISSUE TITLE
4.5 b1 error

### ISSUE THREAD

**Issue by Thenaikan** [toolbox4minecraft/amidst#779] opened 2020-06-25 23:00 UTC
Still generating the attached error when loading map.
![amidst-4 5beta1-error](https://user-images.githubusercontent.com/67339081/85803861-c5403a00-b70d-11ea-9a6c-046fea92b862.jpg)

**Comment by hjpoe** [comment] 2020-06-25 23:30
This seems to be the same as #777.

**Comment by moulins** [comment] 2020-06-26 09:31
Closing as duplicate of #777.

**Closed by moulins** 2020-06-26 09:31 UTC
