### ISSUE TITLE
Profile not found

### ISSUE THREAD

**Issue by DoesntCare** [toolbox4minecraft/amidst#504] opened 2019-07-01 10:22 UTC
June 24 everything was fine.  June 25 a new launcher was automatically downloaded for Minecraft.  After that when I start Amidst it doesn't find the Forge install that it used to find.  I've been comparing the current launcher_profiles JSON file with an older version.  I've also been looking at the Amidst source code but I cannot figure out what the problem is.  This is with MC 1.12.2 and Amidst 4.3-beta3.  What does the program look for to determine the profile is a good one?

**Comment by DoesntCare** [comment] 2019-07-01 13:54
2019-07-01 08:40:07.947 [warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'forge'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:146)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by moulins** [comment] 2019-07-01 20:51
Duplicate of #502.

**Closed by moulins** 2019-07-01 20:51 UTC
