### ISSUE TITLE
Amidst + Server = Crash

### ISSUE THREAD

**Issue by OrbitStorm** [toolbox4minecraft/amidst#139] opened 2016-03-31 06:53 UTC
Apologies for the odd title; shortest description!

When using Amidst v4.1 in conjunction with a Vanilla Minecraft server (v1.9.2), and the Minecraft client, the Java process associated with Amidst will "crash" periodically but Amidst does not produce a crash report; it simply closes. I am able to open Amidst and use any of its features until I attempt to bring the Minecraft client to the foreground, which prompts a Java crash.

Amidst does not crash when used in conjunction with either the client or the server; only when all three are being used. It does not crash on its own either.

To add, I'm fairly certain this isn't an issue with system resources. Six cores and 8GB of system memory should be more than capable of handling all three programs simultaneously (I never exceed 30% usage).

I'm hesitant to label this a bug report but I figured this would be the most appropriate place to discuss the issue.

Thanks!

**Comment by stefandollase** [comment] 2016-03-31 07:31
Thanks for the report. Can you clarify? You use Amidst and a Minecraft Server/Client simultaneously but independent of each other. So you start a Minecraft Server/Client and you start Amidst. The issue only exists if both are running at the same time. There is no issue, if only the Minecraft Client/Server or only Amidst is running. Did I get this correctly?

Also, you talk about Amidst crashing. Can you please post the crash report to this issue?

Additionally, please provide the following information:

* the used operating system and version
* the used Java version

**Comment by OrbitStorm** [comment] 2016-03-31 08:00
Ah.. I misspoke in my original post; corrected that. I'll still clarify more though!

- Amidst, running alone, does not crash.
- Client + Server, does not crash.
- Amidst + Client, does not crash.
- Amidst + Server, does not crash.
- Amidst + Client + Server **does** crash (quite frequently).

When Amidst "crashes", the program itself is not crashing but the associated Java process is (i.e. Java has stopped working) -- at which point Amidst simply closes without producing any sort of error. Both the client and server remain open without issue when this happens. The order in which I launch each of the programs does not matter; Amidst will still "crash". This issue seems to _only_ manifest when attempting to tab or click between Amidst and the client. Minimizing Amidst before bringing the client back to the foreground seemingly prevents this (or maybe I'm just crazy).

My Minecraft client is operating on a standalone version of Java (per the new launcher design), which is Version 8 Update 25.

Currently using Windows 10 Home v1511 (build 10586.164) with Java Version 8 Update 77.

Hopefully this is enough information.

**Comment by stefandollase** [comment] 2016-03-31 16:08
Thanks. Now this is a lot clearer. However, I do not have an explanation for this.

The only starting point I can suggest for further examining the issue is to try this with older versions of Amidst and/or the Minecraft server and/or client. The goal is to see where the issue does occur and where it does not. Maybe, this helps to track the issue down to a version change in one of the programs. If this does not lead to a finding, you might also want to try this with older Java versions, which might be a bit more complicated, especially for the Minecraft client.

**Comment by BlueSteelAUS** [comment] 2016-04-02 03:09
enough memory ?
try running them all on the same version on Java

**Comment by stefandollase** [comment] 2016-04-06 19:02
The OP seems to have lost interest in this issue. Thus I close it.

After all, there is no evidence that this is a bug of Amidst.

**Closed by stefandollase** 2016-04-06 19:02 UTC
Labels: question
