### ISSUE TITLE
Not working on 1.16-pre5 

### ISSUE THREAD

**Issue by almino** [toolbox4minecraft/amidst#770] opened 2020-06-13 13:15 UTC
![image](https://user-images.githubusercontent.com/1825034/84569649-b5644580-ad5e-11ea-817f-16ac37cac840.png)

**Comment by JuniorJedi490** [comment] 2020-06-13 19:39
Duplicate of issue #719. Minecraft versions from 20w11a onward are not currently supported.

**Closed** 2020-06-23 21:49 UTC
Labels: duplicate
