### ISSUE TITLE
Crash on profile selection [1.14]

### ISSUE THREAD

**Issue by seth-rah** [toolbox4minecraft/amidst#482] opened 2019-04-28 10:35 UTC
## Summary

When loading the current latest profile, the application appears to halt.

## Errors

![image](https://user-images.githubusercontent.com/2222634/56863053-e4c8bf00-69b1-11e9-8661-e9fb1df6ea8c.png)

**Comment by moulins** [comment] 2019-04-28 20:59
1.14 isn't supported for the current release (but will be in the next one).

Closing as duplicate of #460.

**Closed by moulins** 2019-04-28 20:59 UTC
