### ISSUE TITLE
Add level.dat history to the File Menu (last viewed level)

### ISSUE THREAD

**Issue by MOARdV** [toolbox4minecraft/amidst#133] opened 2016-03-17 15:20 UTC
This is an ease-of-use request.  I frequently use amidst to open a multi-player save that is not in the default .minecraft directory.  This requires me to navigate through the folders to reach the proper level.dat.  It'd be nice if Amidst could store the "last opened level", with the ability to select it under the file menu.  I realize that gets messy with multiple profiles installed.  I don't know if it's easier to store "last level" per profile, or forget the history when the profile doesn't match the profile used to view those levels, or to reset the profile to match whichever level's being opened.

**Comment by stefandollase** [comment] 2016-03-17 17:14
Thanks for the suggestions. Please have a look at #119, #25 and #112. This issue is a duplicate of these, but your suggestion does indeed have one new point: It might be an option to switch the loaded profile when a world should be loaded from the history that was loaded with another profile before.

However, I added this new point to #119 and close this issue as a duplicate to keep the number of issues discussing this topic small.

**Closed by stefandollase** 2016-03-17 17:14 UTC
Labels: duplicate, feature
