### ISSUE TITLE
Not working on Arch Linux

### ISSUE THREAD

**Issue by samedamci** [toolbox4minecraft/amidst#704] opened 2020-03-01 15:48 UTC
Tested on two computers with Arch Linux, and bootable Debian (on Debian works very well). 
After choosing profile I see only white screen and in logs isn't any error.

Java version on all tested systems: openjdk 11.0.6 2020-01-14
Amidst version: latest, 4.4 from GitHub, I also tested 4.4-beta1
Minecraft profile version: 1.15.2, 1.14.4 (both not working)

![2020-03-01_1583077462](https://user-images.githubusercontent.com/37913333/75628708-ed92ae80-5bdb-11ea-8c53-0cbf09dbd914.png)

**Comment by moulins** [comment] 2020-03-01 17:17
This looks correct; you should be able to generate a world by selecting **File > New From Seed** or **File > New From Random Seed**.

**Comment by samedamci** [comment] 2020-03-01 18:54
> This looks correct; you should be able to generate a world by selecting **File > New From Seed** or **File > New From Random Seed**.

But how I can do this when I don't have menu bar. I see only blank screen after choose profile.

**Comment by moulins** [comment] 2020-03-01 20:04
Try the `Ctrl + N` or `Ctrl + R` shortcuts.

Are you sure the menu bar isn't hidden by the system bar at the top of your screen?

**Comment by samedamci** [comment] 2020-03-02 07:21
> Try the `Ctrl + N` or `Ctrl + R` shortcuts.
> 
> Are you sure the menu bar isn't hidden by the system bar at the top of your screen?

When I press this combinations I see push window but after paste seed still I have blank screen and no, the menu bar isn't hidden by system bar.

**Comment by lberrymage** [comment] 2020-03-09 20:49
I have exactly the same issue with both [java 8](https://gist.github.com/lberrymage/bd62fa693e64c1c21b003572327689d6) and [java 13](https://gist.github.com/lberrymage/3a08f0dc7d49f2172fd6ff3e52b7eafb). After opening a `level.dat` file, the log stops at `[info] fragment cache size increased to 1024`.

**Comment by saemideluxe** [comment] 2020-03-14 05:17
Exact same behavior here.

debian testing (Linux -------- 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux)
openjdk 11
minecraft 1.15.2
amidst v4-4

**Comment by saemideluxe** [comment] 2020-03-14 05:41
Yes, definitely an window manager issue!
If I set _JAVA_AWT_WM_NONREPARENTING=1 as environment variable, it works.

```_JAVA_AWT_WM_NONREPARENTING=1 java -jar amidst-v4-4.jar```

**Comment by lberrymage** [comment] 2020-03-14 22:12
Thanks! That helped! I threw the export in an `/etc/profile.d/` script to prevent typing that every time.

I'm using swaywm by the way

**Comment by moulins** [comment] 2020-03-15 00:25
@saemideluxe Good job for finding the cause of this issue, and providing a solution!

As the issue seems to be caused by a wrongly configured environment, and only occurs on rarely-used window managers, I'll close this.

**Closed by moulins** 2020-03-15 00:25 UTC
Labels: bug
