### ISSUE TITLE
Crash on Startup JavaMC 1.13.1 on WIN10

### ISSUE THREAD

**Issue by RuinPrime** [toolbox4minecraft/amidst#439] opened 2018-08-26 15:08 UTC
Tried opening, after choosing the version my screen immediately started throwing up error windows one after the other, it was at least 40 error message windows before I had to terminate as the CPU usage was getting to the 90's. I had to terminate the process so couldn't copy paste error message but I managed to get a screenshot.

![explorer_2018-08-26_08-51-59](https://user-images.githubusercontent.com/42121163/44629628-604c0b00-a90f-11e8-8f37-9d40220c7bac.png)

Tried again a couple more times and once more with the game closed and the same thing happened. It was working fine with 1.12 but selecting 1.13.1 this happened every time.

**Comment by moulins** [comment] 2018-08-26 16:52
This is a duplicate of #432.

**Closed by moulins** 2018-08-26 16:52 UTC
