### ISSUE TITLE
Amidst

### ISSUE THREAD

**Issue by Tomboy09123** [toolbox4minecraft/amidst#667] opened 2020-01-19 23:51 UTC
amidst keeps crashing

**Comment by moulins** [comment] 2020-01-23 14:46
Are you using the latest version? (v4.4-beta1)

**Comment by Tomboy09123** [comment] 2020-01-24 11:10
yea i am, 1.15.2

**Comment by moulins** [comment] 2020-01-24 16:13
Then, this is fixed in the latest Amidst version (v4.4-beta1). Closing as duplicate of #538.

**Comment by Tomboy09123** [comment] 2020-01-24 23:59
How do I fix it then?

**Comment by moulins** [comment] 2020-01-25 11:10
You can download the latest release [here](https://github.com/toolbox4minecraft/amidst/releases).

**Closed by moulins** 2020-01-25 11:10 UTC
Labels: duplicate
