### ISSUE TITLE
saving screenshot crash?

### ISSUE THREAD

**Issue by pokeball99** [toolbox4minecraft/amidst#67] opened 2016-02-15 00:16 UTC
```
[info] Amidst v4.0-beta8
[info] Biome color profile activated.
[info] using '.minecraft' directory at: 'C:\Users\redacted\AppData\Roaming\.minecraft', libraries: 'C:\Users\redacted\AppData\Roaming\.minecraft\libraries'
[info] using biome color profiles at: 'biome-color-profiles'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
[info] using minecraft launcher profile '*' with versionId '1.8.9'
[info] Loading libraries.
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.7.59\realms-1.7.59.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-platform\6.5\twitch-platform-6.5-natives-windows-64.jar
[info] Found library: C:\Users\redacted\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar
[info] Recognised Minecraft Version 1.8.9 with the magic string "orntlljs[Lle;lx[J[[Jlt".
[info] Reading 1.8.9.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class GenLayer: ase
[info] Found class WorldType: adr
[info] Found class IntCache: asc
[info] Found class BlockInit: kb
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method ase.a(long, @WorldType) -> GenLayer.initializeAllBiomeGenerators2
[info] Classes loaded.
[info] Minecraft load complete.
[warning] unable to write seed to seed history log file
[debug] Attempting to create world with seed: -4172144997902289642, type: Default, and the following generator options:
[debug] 
[info] StrongholdProducer_Original
[info] increasing fragment cache size from 0 to 1024
[info] fragment cache size increased to 1024
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at javax.imageio.ImageIO.write(Unknown Source)
	at amidst.gui.main.Actions.saveImageToFile(Actions.java:328)
	at amidst.gui.main.Actions.saveCaptureImage(Actions.java:220)
	at amidst.gui.main.menu.Menus.lambda$item$49(Menus.java:125)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
``` 
this crashed when i was making a screenshot with the built in snapshot feature

**Comment by stefandollase** [comment] 2016-02-15 02:05
Thanks for reporting it. I will look into this.

I also reformatted the posted crash report.

**Comment by stefandollase** [comment] 2016-02-15 02:35
I am able to reproduce this when I try to save the screenshot to a directory for which I have no writing permissions. Can you confirm, that you tried to do the same thing? Saving the screenshot to a directory without writing permissions? You can verify this by manually trying to create a file in the same directory.

**Comment by Treer** [comment] 2016-02-15 02:37
> [info] StrongholdProducer_Original

Damn, I forgot to remove these log entries, I needed them while debugging to be sure the right Producer was being used. I'll hopefully clean those up tonight.

**Comment by stefandollase** [comment] 2016-02-15 02:40
@Treer I can do it while fixing this bug. There is no need to create a separate pull request for that, since it does not affect any functionality.

**Comment by Treer** [comment] 2016-02-15 02:44
:+1:

**Comment by stefandollase** [comment] 2016-02-15 03:22
This should be fixed by #68. However, I will wait to merge it in until @pokeball99 confirms that the issue was indeed caused by missing writing permissions.

**Comment by pokeball99** [comment] 2016-02-16 01:19
@stefandollase seem to be unable to reproduce this again, can't seem find where i was attemting to save it to before

**Comment by stefandollase** [comment] 2016-02-16 02:24
Thanks for trying it again. If I understand you correctly, you tried to save it in the Libraries folder as described in [this blog post](http://www.howtogeek.com/howto/10283/understanding-the-libraries-feature-in-windows-7/). Not Documents which is a subfolder of Libraries, but Libraries itself?

My impression is, that this is only a kind of virtual folder. Can you directly create files in the Libraries directory? I cannot test this by myself, since I am not a windows user. If you cannot create a file there, this bug should be fixed by #68.

@Treer Maybe you can try this out and maybe try to save a capture image in the Libraries directory with the fixed version? I really need to get a windows system up and running for stuff like this ...

**Comment by pokeball99** [comment] 2016-02-16 02:42
@stefandollase i'm using windows 10, and yes, i had thought i had used pictures to save it in when it crashed, so i had tried to save it their to reproduce it, but it had successfully put it in there, but when trying to do it on the library folder itself, it did crash as seen in that crash log

**Comment by stefandollase** [comment] 2016-02-16 02:47
Thanks for the clarification. The problem is that the crash report does not contain the location where you tried to save the capture image. Now, I will consider this as fixed.

**Closed by stefandollase** 2016-02-16 02:47 UTC
Labels: bug

**Comment by Treer** [comment] 2016-02-16 12:15
I had a play with this, it's not just the Libraries folder, but any folder navigated to underneath that virtual folder.

It's a Java bug which has been [fixed in Java 9](https://bugs.openjdk.java.net/browse/JDK-8003399)

In the mean time your new error handling is good enough, e.g. trying to save to Libraries/Pictures produces this error:

![virtual folder error](https://cloud.githubusercontent.com/assets/6390507/13075943/ec1cb870-d502-11e5-84bc-31cd16a085d5.png)

**Comment by stefandollase** [comment] 2016-02-16 14:36
Thanks for checking this. Since this is a Java bug, we cannot completely fix it. However, it is good to know that it does not result in a crash anymore.
