### ISSUE TITLE
v4.5b3 no longer loading map

### ISSUE THREAD

**Issue by Thenaikan** [toolbox4minecraft/amidst#849] opened 2020-08-13 22:48 UTC
![Capture](https://user-images.githubusercontent.com/67339081/90194572-3c4c9300-dd8d-11ea-95a0-d2891de56bca.JPG)

**Comment by moulins** [comment] 2020-08-13 23:24
Duplicate of #844, this will be fixed in the next release.

**Closed by moulins** 2020-08-13 23:24 UTC
