### ISSUE TITLE
Uncaught Exception: Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by subdigital** [toolbox4minecraft/amidst#230] opened 2016-09-16 15:59 UTC
Was just panning around and got this. Seed -1197425111071708639 if it matters.

```
[info] Amidst v4.2-beta2
[info] Current system time: 2016-09-16 10:55:09.145
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.12'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '1.8.0_101'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/Users/ben/Library/Application Support/minecraft', libraries: '/Users/ben/Library/Application Support/minecraft/libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] using minecraft launcher profile 'subdigital' with versionId '1.10.2'
[info] Loading libraries.
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/com/mojang/realms/1.9.5/realms-1.9.5.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar
[info] Found library: /Users/ben/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
[info] Unable to recognise Minecraft Version with the magic string "rboqmdkcpd[Lls;mp[J[[Jml".
[info] Reading 1.10.2.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class IntCache: aym
[info] Found class WorldType: aii
[info] Found class GenLayer: ayo
[info] Found class BlockInit: kq
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method ayo.a(long, @WorldType) -> GenLayer.initializeAllBiomeGenerators2
[info] Classes loaded.
[info] Minecraft load complete.
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:351)
	at sun.lwawt.macosx.CImage.toImage(CImage.java:256)
	at sun.lwawt.macosx.CImage.lambda$toImage$0(CImage.java:250)
	at sun.awt.image.MultiResolutionCachedImage.getResolutionVariant(MultiResolutionCachedImage.java:66)
	at sun.awt.image.MultiResolutionCachedImage.getBaseImage(MultiResolutionCachedImage.java:106)
	at sun.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:82)
	at sun.awt.image.MultiResolutionCachedImage.getWidth(MultiResolutionCachedImage.java:89)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3262)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3214)
	at com.apple.laf.AquaIcon$CachingScalingIcon.paintIcon(AquaIcon.java:154)
	at javax.swing.plaf.IconUIResource.paintIcon(IconUIResource.java:72)
	at javax.swing.plaf.basic.BasicLabelUI.paint(BasicLabelUI.java:167)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:795)
	at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:757)
	at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:718)
	at amidst.gui.main.SeedPrompt.askForSeed(SeedPrompt.java:129)
	at amidst.gui.main.MainWindow.askForSeed(MainWindow.java:219)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:63)
	at amidst.gui.main.menu.Menus.lambda$item$55(Menus.java:131)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stefandollase** [comment] 2016-09-16 16:58
Thanks for the report. I looked into it, but I cannot see a reason for it. It occurs in [this](https://github.com/toolbox4minecraft/amidst/blob/master/src/main/java/amidst/gui/main/SeedPrompt.java#L129) line, when displaying the seed prompt. This has never been an issue before.

Can you clarify the situation when the issue occurred?

* Was the seed prompt displayed?
* Did you interact with it?
* When exactly did the crash occur?
* Can you reproduce the crash? What are the steps to do so?
* Above the crash report, you mentioned a seed. Where and how did you put it into Amidst? This question assumes, that you did not see the seed prompt.

**Comment by subdigital** [comment] 2016-09-16 17:04
> Can you clarify the situation when the issue occurred?
> 
> Was the seed prompt displayed?

No, it was about 10 minutes after I loaded it.

> Did you interact with it?
Pretty sure the app was not in focus when this happened.

> Can you reproduce the crash? What are the steps to do so?
No, only time I’ve seen it.


> Above the crash report, you mentioned a seed. Where and how did you put it into Amidst? This question assumes, that you did not see the seed prompt.
I used the menu to load a map from my seed.  I then pasted the seed in and pressed Return.  Later on, the app crashed.

**Comment by stefandollase** [comment] 2016-09-16 17:40
Thanks for the details. So you loaded the world by entering the given seed. 10 minutes after you closed the seed prompt, the error occurred? This is strange, since the stack trace suggests that it occurred when you opened the seed prompt.

I just re-read the stack trace and it seems like there are two events executed, because the first event (displaying the seed prompt) invoked the event dispatcher again. To me, it also seems unreasonable that the first event (displaying the seed prompt) is still running, 10 minutes after it was invoked. At some point, the stack should be reduced again, in fact if you interacted with the loaded world it has to have been reduced, because else the world would not be displayed. I am really confused right now.

Since the second event seems to be taken from the event queue, it might be unrelated to the first one. The error occurred in the second event, so there might be two separate issues, or ~~maybe~~ probably it is a threading issue.

One more question: Was the world displayed after you entered the seed? Did you interact with it?

**Comment by subdigital** [comment] 2016-09-16 20:25
> One more question: Was the world displayed after you entered the seed? Did you interact with it?
> 
> 

Yeah I was interacting with the map (panning, zooming).  The error window may have been present right after I entered the seed, but I didn’t notice it.  It didn’t seem to affect the ability to use the app.

**Comment by stefandollase** [comment] 2016-09-17 12:28
> The error window may have been present right after I entered the seed, but I didn’t notice it.

This is probably true. Everything else does not really make sense.

> It didn’t seem to affect the ability to use the app.

This is good to hear. Since I have no idea where this comes from and it did not really affect you, I will close it as *wontfix* for now. If you experience this again, please let me know. If anybody else reports the same issue, we will have to look into this again. Currently, this seems to become a huge time investment to fix a small bug. Since the project is short on developer time, I would like to spend the time for something else.

Anyway, thanks for the report!

**Closed by stefandollase** 2016-09-17 12:28 UTC
Labels: bug, wontfix

**Comment by subdigital** [comment] 2016-09-17 13:00
> Currently, this seems to become a huge time investment to fix a small bug. Since the project is short on developer time, I would like to spend the time for something else.

Totally agree.
