### ISSUE TITLE
Crash upon loading a 1.16.2 profile or snapshot

### ISSUE THREAD

**Issue by fonyo** [toolbox4minecraft/amidst#852] opened 2020-08-15 16:53 UTC
![image](https://user-images.githubusercontent.com/10072275/90317285-291dfc80-df20-11ea-9e56-d3e96ffcad11.png)

**Comment by JuniorJedi490** [comment] 2020-08-15 18:19
Try creating a Minecraft profile that uses the 1.16.1 version, for now?

**Comment by moulins** [comment] 2020-08-15 23:20
Duplicate of #844, closing.

**Closed by moulins** 2020-08-15 23:20 UTC
