### ISSUE TITLE
Amidst 4.1 Crash

### ISSUE THREAD

**Issue by RubenFx** [toolbox4minecraft/amidst#277] opened 2016-11-20 09:52 UTC
Thread (AWT-EventQueue-0,6,main)

**Comment by stefandollase** [comment] 2016-11-20 16:04
This is probably a duplicate of #247. If you keep having the issue in the next release, please open a new bug report and provide more details, especially the complete crash report.

**Closed by stefandollase** 2016-11-20 16:04 UTC
Labels: bug, duplicate
