### ISSUE TITLE
Crash attempting to start amidst

### ISSUE THREAD

**Issue by irtuk** [toolbox4minecraft/amidst#948] opened 2021-03-25 08:51 UTC
[info] Amidst v4.6
[info] Current system time: 2021-03-25 08:50:25.401
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '16'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: 'C:\Users\remoo\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'Latest version' with versionId '1.16.5'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j:66.1 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
[info] Found library com.mojang:javabridge:1.0.22 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.17 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[info] Found library com.mojang:datafixerupper:4.0.26 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:2.1.28 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/remoo/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Unable to recognise Minecraft Version with the magic string "bsacyg$acykapcanqaaxungn$bacu[Jacqabwwacyawdvxafcvzcsw".
[info] Reading 1.16.5.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class NoiseBiomeProvider: bsx$a
[info] Found class ResourceKey: vk
[info] Found class RegistryAccess: gn
[info] Found class DimensionSettings: che
[info] Found class Biome: bsv
[info] Found class Registry: gm
[info] Found class Util: x
[info] Found class BiomeZoomer: bti
[info] Found class RegistryKey: vj
[info] Found class WorldGenSettings: chw
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method chw.a(java.util.Properties) -> WorldGenSettings.create
[info] Classes loaded.
[info] Minecraft load complete.
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.reflect.InaccessibleObjectException: Unable to make void java.awt.Window.setGraphicsConfiguration(java.awt.GraphicsConfiguration) accessible: module java.desktop does not "opens java.awt" to unnamed module @649d209a
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at amidst.gui.main.MultiMonitorFixer.getGCHandle(MultiMonitorFixer.java:34)
	at amidst.gui.main.MultiMonitorFixer.<init>(MultiMonitorFixer.java:28)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:73)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:101)
	at amidst.Application.displayMainWindow(Application.java:76)
	at amidst.gui.profileselect.LocalProfileComponent.loadFinished(LocalProfileComponent.java:156)
	at amidst.threading.WorkerExecutor.lambda$null$8(WorkerExecutor.java:72)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Computeiful** [comment] 2021-04-25 03:25
Having the same issue ^

**Comment by burgerguy** [comment] 2021-05-04 18:59
That whole class is written terribly, my bad. You can bypass the crash by running the jar from the command line by adding `--add-opens java.base/jdk.internal.loader=ALL-UNNAMED` to the parameters, but it still shows up a warning. If you want it to not spit a warning at all, you can use java 8.

**Comment by moulins** [comment] 2021-05-14 16:17
Duplicate of #960.

**Closed by moulins** 2021-05-14 16:17 UTC
