### ISSUE TITLE
Massive Amounts of Errors.

### ISSUE THREAD

**Issue by TheMrPancake** [toolbox4minecraft/amidst#441] opened 2018-08-28 10:44 UTC
I open eclipse, use 1.13.1 and open the seed I want. I then get hundreds of errors all stacked on each other and its really annoying! 
![screen shot 2018-08-28 at 8 42 25 pm](https://user-images.githubusercontent.com/40334355/44718349-22afd380-ab03-11e8-99e2-7fccd2764b1d.png)

**Comment by moulins** [comment] 2018-08-28 16:04
This is a duplicate of #432, and will be fixed in the next release.

**Closed by moulins** 2018-08-28 16:04 UTC
