### ISSUE TITLE
Feat Request: Output in Multiple Resolutions

### ISSUE THREAD

**Issue by GeorgeWL** [toolbox4minecraft/amidst#326] opened 2017-05-18 10:50 UTC
Some of our players have complained that the default res produced is very difficult to view on certain sizes of screen because the level of detail isn't there. 

Would it be possible to add "Output at [Xl/Large/medium/small]" as a tickbox which opens a dropdown option?

**Comment by stefandollase** [comment] 2017-05-18 10:56
This is a duplicate of #245.

**Closed by stefandollase** 2017-05-18 10:56 UTC
Labels: duplicate, feature
