### ISSUE TITLE
Can't open Large Biomes world as Large Biomes

### ISSUE THREAD

**Issue by PKMWM1** [toolbox4minecraft/amidst#812] opened 2020-07-11 21:01 UTC
Whenever I try to oepn my large biome world in AMIDST, it always shows it as default generation, regardless of what I have the default world type set to in AMIDST, the only way I am able to see my world in Large Biomes is to load a world from a seed, put the seed in and select large biomes. However, this doesn't let me load and see player data

**Comment by moulins** [comment] 2020-07-14 22:03
Duplicate of #800; will be fixed in the next release.

**Closed by moulins** 2020-07-14 22:03 UTC
