### ISSUE TITLE
[Bug/Crash] Incompatible with latest MC release

### ISSUE THREAD

**Issue by coraunderhill** [toolbox4minecraft/amidst#853] opened 2020-08-16 12:32 UTC
- **OS:** macOS 10.15.6
- **Java Version:** 8 Update 261
- **Minecraft Version:** 1.16.2
- **Amidst Version:** 4.5 beta 3
- **How to (re)produce:** Choose _Latest Release 1.16.2_ from the Profile Selector window
- **Error Message:**
<img width="982" alt="image" src="https://user-images.githubusercontent.com/868416/90334327-c65d4d00-df81-11ea-98cd-90a9bed3ca84.png">

**Comment by moulins** [comment] 2020-08-16 13:01
Duplicate of #844, closing.

**Closed by moulins** 2020-08-16 13:01 UTC
