### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Litro740** [toolbox4minecraft/amidst#379] opened 2018-03-21 21:25 UTC
I keep getting this error message whenever I try loading a profile in Amidst. I really don't know what to do...

https://user-images.githubusercontent.com/25109835/37736943-ad7f5c3c-2d28-11e8-90ec-4473e83cdca0.png

**Comment by stefandollase** [comment] 2018-04-08 09:43
This is a duplicate of #378

**Closed by stefandollase** 2018-04-08 09:43 UTC
Labels: bug, duplicate
