### ISSUE TITLE
The Location of Dungons e.g Zombies, Skeletons

### ISSUE THREAD

**Issue by jjf1708** [toolbox4minecraft/amidst#149] opened 2016-04-07 16:55 UTC
It would be great if there was a icon on your application of a location of a dungon as it would be handy if you would be able to know the location of a dungon instead of playing 300 hours of a World and you cannot find one.

**Comment by stefandollase** [comment] 2016-04-07 17:46
I agree, that this is would be useful. However, this is a duplicate of #57 and is currently out of scope for Amidst.

**Closed by stefandollase** 2016-04-07 17:46 UTC
Labels: duplicate, feature
