### ISSUE TITLE
Amidst error when working with 1.16.2

### ISSUE THREAD

**Issue by CuteZombie7** [toolbox4minecraft/amidst#848] opened 2020-08-13 04:11 UTC
![批注 2020-08-13 120834](https://user-images.githubusercontent.com/48387243/90093386-0ba13500-dd5e-11ea-944d-532e869f5cf8.png)

**Comment by moulins** [comment] 2020-08-13 09:37
Duplicate of #844, closing.

**Closed by moulins** 2020-08-13 09:37 UTC
