### ISSUE TITLE
Amidst error when selecting profile (1.16.1)

### ISSUE THREAD

**Issue by Koko37yt** [toolbox4minecraft/amidst#796] opened 2020-07-01 13:37 UTC
Well when i select the latest version profile i just get this error :/
Any way to fix it?

![Hmm](https://user-images.githubusercontent.com/67695899/86250389-cca19080-bbb0-11ea-9994-64b0c6abb0b9.PNG)

**Comment by moulins** [comment] 2020-07-01 16:11
Does this still happens with the latest Amidst version? (v4.5-beta2)

**Comment by Koko37yt** [comment] 2020-07-01 18:43
I was using v4.4 switched to v4.5-beta2 and it's working now thx

**Comment by gstroy** [comment] 2020-08-16 23:13
I'm also getting this issue, with 4.4 and with the latest snapshot (might be a mac issue on OSX 10.15)

![Screen Shot 2020-08-16 at 6 10 41 PM](https://user-images.githubusercontent.com/10751126/90346117-e590c480-dfeb-11ea-8e69-599b442ed499.png)

**Comment by moulins** [comment] 2020-08-19 19:30
Duplicate of #857, closing.

**Closed by moulins** 2020-08-19 19:30 UTC
Labels: waiting-for-answer
