### ISSUE TITLE
No profiles at all.

### ISSUE THREAD

**Issue by NillerESSKEETIT** [toolbox4minecraft/amidst#505] opened 2019-07-01 12:50 UTC
It worked just fine 2 days ago, but now it just doesn't show any profiles. Does this have anything to do with the new Minecraft launcher? 

Please help, Niller.

**Comment by moulins** [comment] 2019-07-01 20:49
Duplicate of #502.

The profile should work if you select a specific Minecraft version instead of "Latest snapshot/release".

**Closed by moulins** 2019-07-01 20:49 UTC

**Comment by NillerESSKEETIT** [comment] 2019-07-02 15:10
It's so much slower, than it was 3 days ago. Do you know what causes this issue?

-Niller
