### ISSUE TITLE
Add SVG export option

### ISSUE THREAD

**Issue by GeorgeWL** [toolbox4minecraft/amidst#714] opened 2020-03-11 10:29 UTC
SVG format represents images as a series of vectors, which allows them to be (near) infinitely scalable in size without any loss of quality. The only real issue is some older computers are unable to read the format, or can only view it by putting the image into an "SVG viewer" app.

Can imagine this would come in handy nonetheless.

**Comment by moulins** [comment] 2020-03-15 00:29
Duplicate of #327. If you want to restart the discussion of this feature, please comment on the original issue's thread.

**Closed by moulins** 2020-03-15 00:29 UTC

**Comment by GeorgeWL** [comment] 2020-03-17 10:46
oops...I forgotten I'd already made the issue.
