### ISSUE TITLE
Amidst Crashed

### ISSUE THREAD

**Issue by AlanAlef** [toolbox4minecraft/amidst#240] opened 2016-10-13 17:33 UTC
Hi :)

I try to use Amidst and it crashed, every time that i try to use it in a deed or random seed it crashed i am using Amidst version 3.7.

Help me!!!

**Comment by MattSturgeon** [comment] 2016-10-14 04:05
Before reporting issues, it is usually a good idea to check if you can reproduce the problem on the [latest version](https://github.com/toolbox4minecraft/amidst/releases).

If it is still an issue in 4.2 beta 2, please try to decribe in more detail how to produce the crash and share the crashlog via pastebin or similar.

If you cannot reproduce the crash in the latest version, then please feel free to close the issue :)

**Comment by BigAlanM** [comment] 2016-10-14 10:28
Another point is that Amidst WILL NOT work if you try to get it to use a profile for a modified copy of Minecraft (this includes Minecraft modded with Optifine).
You MUST use Amidst with a totally vanilla copy of Minecraft.jar for the version you designate.

**Comment by stefandollase** [comment] 2016-10-20 11:58
The OP seems to have lost interest in this issue. Thus I close it.

**Closed by stefandollase** 2016-10-20 11:58 UTC
Labels: bug, invalid
