### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by bluepenhorwood** [toolbox4minecraft/amidst#281] opened 2016-11-20 17:52 UTC
Amidst error. It wont load any saved worlds.
"Amidst has encounted an uncaught exception on the thread thread[AWT-EventQueue-0,6,main]"

**Comment by stefandollase** [comment] 2016-11-20 18:20
This is probably a duplicate of #247. If you keep having the issue in the next release, please open a new bug report and provide more details, especially the complete crash report.

**Closed by stefandollase** 2016-11-20 18:20 UTC
Labels: bug, duplicate
