### ISSUE TITLE
[FEATURE REQUEST] Flag places on a map.

### ISSUE THREAD

**Issue by twboom** [toolbox4minecraft/amidst#789] opened 2020-06-29 15:01 UTC
I use Amidst mostly as a map to find the way to my friends on my survival MC server, but I keep looking up the coordinates. So it would be nice to add a function to attach a note/picture to a coordinate. I imagine it would something like this.
![Map_6](https://user-images.githubusercontent.com/28734514/86021091-00ea4500-ba29-11ea-869a-ceb1f1ce80e1.jpg)
Currently we make those maps in Photoshop, but then they aren't intractable anymore.

It would be extra handy if you can just enter a name of a MC player and it would grab the head from something like namemc.

To make this all more functional I suggest you can save things, in a .txt (or something like that) and include the things like the seed (and the worldspawn as people can move them) so that people can send them to each other and they can load that file in Amidst and see everything.

**Comment by moulins** [comment] 2020-06-30 00:20
Duplicate of #475.

**Closed by moulins** 2020-06-30 00:20 UTC
