### ISSUE TITLE
Crash when trying to load level.dat with Minecraft 1.11 Pre 1

### ISSUE THREAD

**Issue by Elwin1010** [toolbox4minecraft/amidst#258] opened 2016-11-15 19:58 UTC
This is the stacktrace:
```
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at amidst.clazz.symbolic.SymbolicClass.callStaticMethod(SymbolicClass.java:74)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getGenLayers(LocalMinecraftInterface.java:104)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:78)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:97)
	at amidst.mojangapi.world.WorldBuilder.fromSaveGame(WorldBuilder.java:73)
	at amidst.mojangapi.MojangApi.createWorldFromSaveGame(MojangApi.java:133)
	at amidst.gui.main.Actions.openSaveGame(Actions.java:92)
	at amidst.gui.main.menu.AmidstMenuBuilder$$Lambda$45/382428792.run(Unknown Source)
	at amidst.gui.main.menu.Menus.lambda$item$55(Menus.java:131)
	at amidst.gui.main.menu.Menus$$Lambda$43/1054389111.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

Seems like Amidst doesn't recognize some file in the Minecraft 1.11 Pre 1 snapshot.

**Comment by stefandollase** [comment] 2016-11-15 22:20
This is a duplicate of #247.

**Closed by stefandollase** 2016-11-15 22:20 UTC
Labels: bug, duplicate
