### ISSUE TITLE
Jump to biomes/structures

### ISSUE THREAD

**Issue by RTamaasP** [toolbox4minecraft/amidst#889] opened 2020-08-31 15:44 UTC
Hi Creators,
I've seen sadly when you've taken out of focus the render saving... but that's not why I am here (but was one of the 2 before I've seen that discussion.). So the other and only mentionable idea is that I suppose to be able to jump to structures with a scrolling menu. Like this:
 
- Jump to... >
     - Structure... >
          - Pilagger outpost
          - Witch Hut
          - etc.
     - Biome... >
          - Mesa Plateau
          - Tall Birch Hills
          - etc.

And if added, I think should be added a selection betveen "nearest from actual" and "nearest from player".
Oh, and I've almost forgotten to justify why it is needed: This is good for the rare biomes and structures, because the map doesn't load too fast :/ and it can save some time.

**Comment by moulins** [comment] 2020-08-31 17:14
Duplicate of #120; unfortunately, this is a big feature with lots of questions to answer, so progress has stalled for quite some time now. :(

**Closed by moulins** 2020-08-31 17:14 UTC
