### ISSUE TITLE
how to explore the nether?

### ISSUE THREAD

**Issue by thegamerx1** [toolbox4minecraft/amidst#691] opened 2020-02-08 13:53 UTC
![image](https://user-images.githubusercontent.com/34986564/74086395-bae51280-4a82-11ea-997f-125f67d760d8.png)
theres no nether option

**Comment by burgerguy** [comment] 2020-02-09 00:26
Currently, amidst can't do this. I'm working on implementing it, but it may take a while.

**Comment by moulins** [comment] 2020-02-10 02:24
Closing as duplicate of #692.

**Closed by moulins** 2020-02-10 02:24 UTC
