### ISSUE TITLE
Large Biomes not recognised under 1.16

### ISSUE THREAD

**Issue by Werrf** [toolbox4minecraft/amidst#828] opened 2020-07-25 03:41 UTC
When opening a saved game created in version 1.16, the world type is always set to "Default" even when the world was created with large biomes. Player location is identified correctly, but the biome is incorrect. Using "New from seed" and entering the seed the world was created from does appear to generate the correct Large Biomes map; it just doesn't get the Large Biomes flag from the saved game.

**Comment by burgerguy** [comment] 2020-07-26 20:24
This has been fixed and will be shipped in the next version.

**Comment by moulins** [comment] 2020-08-06 15:40
Duplicate of #800.

**Closed by moulins** 2020-08-06 15:40 UTC
