### ISSUE TITLE
Unable to locate stronghold correctly

### ISSUE THREAD

**Issue by ProClifo** [toolbox4minecraft/amidst#954] opened 2021-04-05 10:24 UTC
Minecraft version: 1.16.5
Amidst v4.6
Not sure what Java version I have, but it's probably not relevant in this issue

I'm using Amidst to find strongholds in my world, but the map is inaccurate. In Amidst, it says there's a stronghold at -15584, 14016, but when I teleport there, there is no stronghold. Instead, when I type /locate stronghold, the nearest stronghold is 1119 blocks away, at -14840, 14920. I made sure that both Amidst and Minecraft were using the 1.16.5 version.

To reproduce the problem, here is the seed: 5797705914173781750

**Comment by moulins** [comment] 2021-05-14 17:23
This is a duplicate of #785, and will be fixed in the next Amidst release.

**Closed by moulins** 2021-05-14 17:23 UTC
