### ISSUE TITLE
4.5-Beta 1. Crashes on 1.16.1 open save game 

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#782] opened 2020-06-26 22:29 UTC
I tried 4.5-Beta 1 with 1.15.2 and all seemed good.
Changed to 1.16.1 and Ctrl-R works as does Crtl-N with both numeric and text seeds.
HOWEVER Open Save Game works with 1.15.2 but NOT with 1.16.1.

Also the error window has no scrolling function to see the entire log, and no entry is created in the log folder and the text in the error window can't be marked and copied.

EDIT: OK I found I could View Log Messages in a scrollable window. 

Here is the text of the error window.
[warning] java.io.IOException: [JNBT] Invalid tag type: 12.
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:208)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:96)
	at amidst.mojangapi.file.nbt.NBTUtils.readTagFromFile(NBTUtils.java:22)
	at amidst.mojangapi.file.nbt.LevelDatNbt.from(LevelDatNbt.java:17)
	at amidst.mojangapi.file.service.SaveDirectoryService.readLevelDat(SaveDirectoryService.java:71)
	at amidst.mojangapi.file.MinecraftInstallation.newSaveGame(MinecraftInstallation.java:95)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:78)
	at amidst.gui.main.Actions.openSaveGame(Actions.java:107)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:138)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by UncleBobbySr** [comment] 2020-06-26 23:55
Same problem with me too.

**Comment by ghastlybespoke4** [comment] 2020-06-27 15:23
I have experienced the same issue. I can currently only view one of my 1,16,1 worlds with this release.

**Comment by lightchao0** [comment] 2020-06-29 02:42
I too am having this issue, if it helps narrow down the problem any, I'm able to open worlds that haven't been opened in 1.16 or any of it's snapshots.

**Comment by moulins** [comment] 2020-06-29 23:39
Closing as duplicate of #777

**Closed by moulins** 2020-06-29 23:39 UTC
