### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by crossway777** [toolbox4minecraft/amidst#293] opened 2016-11-22 00:15 UTC
Amidst has encountered an unknown exception on the thread Thread[AWT-EventQueue-0,6,main]

```
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Unable to recognise Minecraft Version with the magic string "rroumhkfph[Llw;mt[J[[Jmp".
[info] Reading 1.11.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class GenLayer: bah
[info] Found class WorldType: ajv
[info] Found class IntCache: baf
[info] Found class BlockInit: kt
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method bah.a(long, @WorldType) -> GenLayer.initializeAllBiomeGenerators2
[info] unable to find the real class method bah.a(long, @WorldType, String) -> GenLayer.initializeAllBiomeGenerators3
[info] Classes loaded.
[info] Minecraft load complete.
[info] Not writing to seed history file, because it does not exist: history.txt
[info] Creating world with seed '-28090936150918956' and type 'Default'
[info] Using the following generator options: 
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at amidst.clazz.symbolic.SymbolicClass.callStaticMethod(SymbolicClass.java:74)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getGenLayers(LocalMinecraftInterface.java:104)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:78)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:97)
	at amidst.mojangapi.world.WorldBuilder.fromSeed(WorldBuilder.java:52)
	at amidst.mojangapi.MojangApi.createWorldFromSeed(MojangApi.java:118)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:78)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:64)
	at amidst.gui.main.menu.Menus.lambda$item$55(Menus.java:131)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by stefandollase** [comment] 2016-11-22 23:37
This is a duplicate of #247. Please download the latest version of Amidst from:

https://github.com/toolbox4minecraft/amidst/releases

**Closed by stefandollase** 2016-11-22 23:37 UTC
Labels: bug, duplicate
