### ISSUE TITLE
amidst bug 

### ISSUE THREAD

**Issue by night125672** [toolbox4minecraft/amidst#814] opened 2020-07-14 07:38 UTC
theres a bug on amidst were i cant leave the end

**Comment by moulins** [comment] 2020-08-06 16:04
Can't you switch dimensions in the `Layers` menu?

**Comment by Cactooz** [comment] 2020-11-01 17:51
You can change to overworld in the `Layers` men. There are no problems in the latest release to move between overworld and the end.

**Comment by moulins** [comment] 2020-12-06 01:17
Closing as duplicate of #512.

**Closed by moulins** 2020-12-06 01:17 UTC
Labels: bug
