### ISSUE TITLE
https://github.com/toolbox4minecraft/amidst/issues/new

### ISSUE THREAD

**Issue by LittleGamer2500** [toolbox4minecraft/amidst#944] opened 2021-02-25 05:42 UTC
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: unable to load resource: '/amidst/metadata.properties'
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:50)
	at amidst.Amidst.createMetadata(Amidst.java:61)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.util.Properties$LineReader.readLine(Unknown Source)
	at java.util.Properties.load0(Unknown Source)
	at java.util.Properties.load(Unknown Source)
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:45)
	... 3 more

**Comment by moulins** [comment] 2021-05-14 16:26
Duplicate of #956.

**Closed by moulins** 2021-05-14 16:26 UTC
