### ISSUE TITLE
Pillager outposts and shipwreck locations issues

### ISSUE THREAD

**Issue by spiiross** [toolbox4minecraft/amidst#801] opened 2020-07-02 11:53 UTC
seed: -6554930108834998883 -> Pillager Outposts locations not showing at spawn
seed: 5615263465277602084 -> Incorrect shipwreck locations (-376,1624)

**Comment by moulins** [comment] 2020-07-14 22:44
Which version of Minecraft are you using?

**Comment by spiiross** [comment] 2020-07-15 06:47
i'm currently on 1.16.1, but i think the issue not with the version because while i was on 1.15.2 the pillager outposts didn't show on the map. Needs to be next to spawn.

**Comment by burgerguy** [comment] 2020-07-25 02:45
The issue is actually with the version. If you open a profile on 1.15.2, the shipwreck won't be there. If you open a profile on 1.16.1, it will.

**Comment by spiiross** [comment] 2020-07-26 10:50
Oh that's why , thanks for the info and sorry for wasting your time. Also i'd like to say if you can change the profile mechanics and let the user select the version that will be better, because right now i can't load any profile from 1.14.x or 1.15.x and it says is 1.16.1 Latest Version and 1.16.1 Snapshot (i don't have this one).
Thanks again for the help, have a great day.

**Comment by burgerguy** [comment] 2020-07-27 23:35
@spiiross For other versions you have to make a different profile in the Minecraft launcher for it to show up in amidst.

**Comment by spiiross** [comment] 2020-07-28 11:41
About that, i have 4 profile already but i found two Minecraft folder for some reason and now it works fine.
Thanks you again and have a lovely day .

**Comment by moulins** [comment] 2020-08-06 21:52
Closing as invalid.

**Closed by moulins** 2020-08-06 21:52 UTC
Labels: bug, waiting-for-answer
