### ISSUE TITLE
Spammed with error messages (Unable to get biome data)

### ISSUE THREAD

**Issue by Zeetheus** [toolbox4minecraft/amidst#447] opened 2018-08-31 23:00 UTC
The log is far too long for me to post here, but I can paste a fragment. I might be doing something terribly wrong, but I hope it's worth reporting.

I had a download of a 1.12 multiplayer world region folder (only region, not region1, region2, or the rest). I imported this to singleplayer in 1.13.1, and went looking through the world in singleplayer for a coral reef biome. There were chunk errors of course, but I was mainly looking for coords to check in multiplayer. It was taking too long, so I downloaded the current Amidst beta exe.

When opening Amidst I chose 1.13.1, and opened the file through the singleplayer save data. It told me the data was a mix of singleplayer and multiplayer data. No matter which selection I pick (I did try singleplayer, multiplayer, and both) I would get an endless amount of error popups that ate up an entire GB of ram and would not stop. The only way to stop it involved opening task manager and force-closing the java process.

Here is the beginning of the txt file with the error data:

```
[18:39:25] [AWT-EventQueue-0/INFO]: [STDOUT]: [info] loading player locations
[18:39:25] [Thread-9/INFO]: [STDOUT]: [info] using player from level.dat
[18:39:25] [AWT-EventQueue-0/INFO]: [STDOUT]: [info] increasing fragment cache size from 0 to 1024
[18:39:25] [AWT-EventQueue-0/INFO]: [STDOUT]: [info] fragment cache size increased to 1024
[18:39:26] [Thread-3/INFO]: [STDOUT]: [error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceException: unable to get biome data
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:184)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeData(LocalMinecraftInterface.java:99)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.getBiomeData(LoggingMinecraftInterface.java:18)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.getBiomeData(BiomeDataOracle.java:177)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.populateArray(BiomeDataOracle.java:32)
	at amidst.fragment.Fragment.populateBiomeData(Fragment.java:110)
	at amidst.fragment.loader.BiomeDataLoader.doLoad(BiomeDataLoader.java:34)
	at amidst.fragment.loader.BiomeDataLoader.load(BiomeDataLoader.java:23)
	at amidst.fragment.layer.LayerLoader.loadAll(LayerLoader.java:38)
	at amidst.fragment.layer.LayerManager.loadAll(LayerManager.java:58)
	at amidst.fragment.FragmentQueueProcessor.loadFragment(FragmentQueueProcessor.java:79)
	at amidst.fragment.FragmentQueueProcessor.processQueues(FragmentQueueProcessor.java:50)
	at amidst.gui.main.viewer.PerViewerFacadeInjector.onFragmentLoaderTick(PerViewerFacadeInjector.java:159)
	at amidst.threading.ThreadMaster$6.run(ThreadMaster.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:182)
	... 20 more

[18:39:26] [Thread-3/INFO]: [STDOUT]: [error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceException: unable to get biome data
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:184)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeData(LocalMinecraftInterface.java:99)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.getBiomeData(LoggingMinecraftInterface.java:18)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.getBiomeData(BiomeDataOracle.java:177)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.getQuarterResolutionBiomeData(BiomeDataOracle.java:168)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.findValidLocation(BiomeDataOracle.java:118)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.findValidLocationAtMiddleOfChunk(BiomeDataOracle.java:106)
	at amidst.mojangapi.world.icon.producer.StrongholdProducer_Base.findStronghold(StrongholdProducer_Base.java:71)
	at amidst.mojangapi.world.icon.producer.StrongholdProducer_Base.doCreateCache(StrongholdProducer_Base.java:42)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.createCache(CachedWorldIconProducer.java:65)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.getCache(CachedWorldIconProducer.java:53)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.produce(CachedWorldIconProducer.java:19)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.produce(CachedWorldIconProducer.java:12)
	at amidst.mojangapi.world.icon.producer.WorldIconProducer.getAt(WorldIconProducer.java:16)
	at amidst.fragment.loader.WorldIconLoader.doLoad(WorldIconLoader.java:47)
	at amidst.fragment.loader.WorldIconLoader.load(WorldIconLoader.java:34)
	at amidst.fragment.layer.LayerLoader.loadAll(LayerLoader.java:38)
	at amidst.fragment.layer.LayerManager.loadAll(LayerManager.java:58)
	at amidst.fragment.FragmentQueueProcessor.loadFragment(FragmentQueueProcessor.java:79)
	at amidst.fragment.FragmentQueueProcessor.processQueues(FragmentQueueProcessor.java:50)
	at amidst.gui.main.viewer.PerViewerFacadeInjector.onFragmentLoaderTick(PerViewerFacadeInjector.java:159)
	at amidst.threading.ThreadMaster$6.run(ThreadMaster.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:182)
	... 28 more
```

**Comment by moulins** [comment] 2018-09-02 13:35
Duplicate of #432.

**Closed by moulins** 2018-09-02 13:35 UTC
