### ISSUE TITLE
Wrong biomes names

### ISSUE THREAD

**Issue by Jyris-Clipton** [toolbox4minecraft/amidst#747] opened 2020-05-01 21:22 UTC
Good evening,

Since Minecraft Java Version 1.13, some biome names have changed, but not adjusted in Amdist. Here is the list (ID / New name / Old Name):

  3 Mountains (Extreme Hills)
 12 Snowy Tundra (Ice Plains)
 13 Snowy Mountains (Ice Mountains)
 14 Mushroom Fields (Mushroom Island)
 15 Mushroom Field Shore (Mushroom Island Shore)
 18 Wooded Hills (Forest Hills)
 25 Stone Shore (Stone Beach)
 26 Snowy Beach (Cold Beach)
 29 Dark Forest (Roofed Forest)
 30 Snowy Taiga (Cold Taiga)
 31 Snowy Taiga Hills (Cold Taiga Hills)
 32 Giant Tree Taiga (Mega Taiga)
 33 Giant Tree Taiga Hills (Mega Taiga Hills)
 34 Wooded Mountains (Extreme Hills+)
 37 Badlands (Mesa)
 38 Wooded Badlands Plateau (Mesa Plateau F)
 39 Badlands Plateau (Mesa Plateau)
 40 Small End Inslands (The End - Floating Islands)
 41 End Midlands (The End - Medium island)
 42 End Highlands (The End - High Island)
 43 End Barrens (The - End Barren Island)
 48 Deep Lukewarm Ocean (Lukewarm Deep Ocean)
 49 Deep Cold Ocean (Cold Deep Ocean)
 50 Deep Frozen Ocean (Frozen Deep Ocean)
130 Desert Lakes (Desert M)
131 Gravelly Mountains (Extreme Hills M)
133 Taiga Mountains (Taiga M)
134 Swamp Hills (Swampland M)
140 Ice Spikes (Ice Plains Spike)
149 Modified Jungle (Jungle M)
151 Modified Jungle Edge (Jungle Edge M)
155 Tall Birch Forest (Birch Forest M)
156 Tall Birch Hills (Birch Forest Hills M)
157 Dark Forest Hills (Roofed Forest M)
158 Snowy Taiga Mountains (Cold Taiga M)
160 Giant Spruce Taiga (Mega Spruce Taiga)
161 Giant Spruce Taiga Hills (Mega Spruce Taiga (Hills))
162 Gravelly Mountains+ (Extreme Hills+ M)
163 Shattered Savanna (Savanna M)
164 Shattered Savanna Plateau (Savanna Plateau M)
165 Eroded Badlands (Mesa (Bryce))
166 Modified Wooded Badlands Plateau (Mesa Plateau F M)
167 Modified Badlands Plateau (Mesa Plateau M)

And another thing I would like to say is that we could have a option to "Go to Woodland Mansion", since it's rarer.

Here's the link where the information was taken from: 
https://minecraft.gamepedia.com/Biome
https://minecraft.gamepedia.com/Java_Edition_1.13

Thanks for your attention,

Jyris Clipton.

**Comment by moulins** [comment] 2020-05-02 14:51
Duplicate of #569 (the issue name isn't very good...).

This has been fixed by PR #726, and will be included in the next release. ;)

**Closed by moulins** 2020-05-02 14:51 UTC
