### ISSUE TITLE
amidst-v4-3-beta4.exe crash Windows 10

### ISSUE THREAD

**Issue by mglogan** [toolbox4minecraft/amidst#446] opened 2018-08-31 16:58 UTC
G'day Folks, 

I tried the version in the subject and it crashed when trying to generate the world -- both from a 1.13 save and from a selected seed (seed=1).  A large number of error windows appeared (and more kept arriving until I killed the process).

Here a sample from the log:
[12:33:13] [AWT-EventQueue-0/INFO]: [STDOUT]: [info] loading player locations
[12:33:13] [Thread-5/INFO]: [STDOUT]: [info] using player from level.dat
[12:33:13] [AWT-EventQueue-0/INFO]: [STDOUT]: [info] increasing fragment cache size from 0 to 1024
[12:33:13] [AWT-EventQueue-0/INFO]: [STDOUT]: [info] fragment cache size increased to 1024
[12:33:14] [Thread-3/INFO]: [STDOUT]: [error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceException: unable to get biome data
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:184)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeData(LocalMinecraftInterface.java:99)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.getBiomeData(LoggingMinecraftInterface.java:18)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.getBiomeData(BiomeDataOracle.java:177)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.populateArray(BiomeDataOracle.java:32)
	at amidst.fragment.Fragment.populateBiomeData(Fragment.java:110)
	at amidst.fragment.loader.BiomeDataLoader.doLoad(BiomeDataLoader.java:34)
	at amidst.fragment.loader.BiomeDataLoader.load(BiomeDataLoader.java:23)
	at amidst.fragment.layer.LayerLoader.loadAll(LayerLoader.java:38)
	at amidst.fragment.layer.LayerManager.loadAll(LayerManager.java:58)
	at amidst.fragment.FragmentQueueProcessor.loadFragment(FragmentQueueProcessor.java:79)
	at amidst.fragment.FragmentQueueProcessor.processQueues(FragmentQueueProcessor.java:50)
	at amidst.gui.main.viewer.PerViewerFacadeInjector.onFragmentLoaderTick(PerViewerFacadeInjector.java:159)
	at amidst.threading.ThreadMaster$6.run(ThreadMaster.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:182)
	... 20 more

[12:33:14] [Thread-3/INFO]: [STDOUT]: [error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceException: unable to get biome data
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:184)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeData(LocalMinecraftInterface.java:99)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.getBiomeData(LoggingMinecraftInterface.java:18)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.getBiomeData(BiomeDataOracle.java:177)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.getQuarterResolutionBiomeData(BiomeDataOracle.java:168)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.findValidLocation(BiomeDataOracle.java:118)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.findValidLocationAtMiddleOfChunk(BiomeDataOracle.java:106)
	at amidst.mojangapi.world.icon.producer.StrongholdProducer_Base.findStronghold(StrongholdProducer_Base.java:71)
	at amidst.mojangapi.world.icon.producer.StrongholdProducer_Base.doCreateCache(StrongholdProducer_Base.java:42)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.createCache(CachedWorldIconProducer.java:65)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.getCache(CachedWorldIconProducer.java:53)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.produce(CachedWorldIconProducer.java:19)
	at amidst.mojangapi.world.icon.producer.CachedWorldIconProducer.produce(CachedWorldIconProducer.java:12)
	at amidst.mojangapi.world.icon.producer.WorldIconProducer.getAt(WorldIconProducer.java:16)
	at amidst.fragment.loader.WorldIconLoader.doLoad(WorldIconLoader.java:47)
	at amidst.fragment.loader.WorldIconLoader.load(WorldIconLoader.java:34)
	at amidst.fragment.layer.LayerLoader.loadAll(LayerLoader.java:38)
	at amidst.fragment.layer.LayerManager.loadAll(LayerManager.java:58)
	at amidst.fragment.FragmentQueueProcessor.loadFragment(FragmentQueueProcessor.java:79)
	at amidst.fragment.FragmentQueueProcessor.processQueues(FragmentQueueProcessor.java:50)
	at amidst.gui.main.viewer.PerViewerFacadeInjector.onFragmentLoaderTick(PerViewerFacadeInjector.java:159)
	at amidst.threading.ThreadMaster$6.run(ThreadMaster.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: bac cannot be cast to java.lang.Integer
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:182)
	... 28 more

**Comment by Malangs** [comment] 2018-08-31 18:28
Having the same promlem. I think it's a duplicate of #432.

**Comment by moulins** [comment] 2018-08-31 21:04
@Malangs is right, it's a duplicate. It is already fixed on `master`, and I'll probably do a release this week-end.

**Closed by moulins** 2018-08-31 21:04 UTC
