### ISSUE TITLE
Crash with 1.13.1 world / profile

### ISSUE THREAD

**Issue by rm-code** [toolbox4minecraft/amidst#437] opened 2018-08-25 20:59 UTC
```
[22:56:43] [Thread-2/INFO]: [STDOUT]: [error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceException: unable to get biome data
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:184)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeData(LocalMinecraftInterface.java:99)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.getBiomeData(LoggingMinecraftInterface.java:18)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.getBiomeData(BiomeDataOracle.java:177)
	at amidst.mojangapi.world.oracle.BiomeDataOracle.populateArray(BiomeDataOracle.java:32)
	at amidst.fragment.Fragment.populateBiomeData(Fragment.java:110)
	at amidst.fragment.loader.BiomeDataLoader.doLoad(BiomeDataLoader.java:34)
	at amidst.fragment.loader.BiomeDataLoader.load(BiomeDataLoader.java:23)
	at amidst.fragment.layer.LayerLoader.loadAll(LayerLoader.java:38)
	at amidst.fragment.layer.LayerManager.loadAll(LayerManager.java:58)
	at amidst.fragment.FragmentQueueProcessor.loadFragment(FragmentQueueProcessor.java:79)
	at amidst.fragment.FragmentQueueProcessor.processQueues(FragmentQueueProcessor.java:50)
	at amidst.gui.main.viewer.PerViewerFacadeInjector.onFragmentLoaderTick(PerViewerFacadeInjector.java:159)
	at amidst.threading.ThreadMaster$6.run(ThreadMaster.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getBiomeId(LocalMinecraftInterface.java:182)
	... 19 more
```

**Comment by rm-code** [comment] 2018-08-25 21:00
I can provide the full log if you want, but it has several thousand lines of text as far as I can tell :P

**Comment by moulins** [comment] 2018-08-25 21:51
This is a duplicate of #432; it will be fixed in the next release.

**Closed by moulins** 2018-08-25 21:51 UTC

**Comment by rm-code** [comment] 2018-08-25 22:02
Ah thanks! I forgot to search the closed issues.
