### ISSUE TITLE
Profiles not found -1.16.1 (Reinstalled launcher)

### ISSUE THREAD

**Issue by swabfu** [toolbox4minecraft/amidst#850] opened 2020-08-14 18:38 UTC
I recently deleted my .minecraft and reinstalled my launcher. I've been playing for around 3 days now, on both my Fabric 1.16.1 profile, and on a vanilla 1.16.1 profile. Since I reinstalled my launcher I can't open Amidst as I just get an error message when trying to load profiles. I've also read past issues where the issue was that certain files hadn't been created in their new .minecraft yet, but I already have these (ie launcher_profiles.json). Attached is a picture with my error message. Thanks in advance.
![Annotation 2020-08-14 203412](https://user-images.githubusercontent.com/65395037/90282032-f87d8a80-de6d-11ea-8568-ce72b4851300.png)

**Comment by JuniorJedi490** [comment] 2020-08-15 18:17
Duplicate of issue #852 (Crash upon loading a 1.12.2 version or snapshot)

**Comment by moulins** [comment] 2020-08-15 23:21
You get this error because Amidst doesn't support Minecraft 1.16.2 yet. (It will in the next release)

Duplicate of #844, closing.

**Closed by moulins** 2020-08-15 23:21 UTC
