### ISSUE TITLE
Issue when trying to load map from save file OR seed

### ISSUE THREAD

**Issue by Kiladra** [toolbox4minecraft/amidst#600] opened 2019-12-23 17:12 UTC
Here is the error report I get (see attached file).

The window asked to report this here so there you go.

I was trying to load my map from save file, then from seed, and both times it failed.
I'm using Java version 1.15.1
[Crash amidst.txt](https://github.com/toolbox4minecraft/amidst/files/3995692/Crash.amidst.txt)

**Comment by moulins** [comment] 2019-12-28 23:41
Duplicate of #538; this is fixed in the latest release (v4.4-beta1)

**Closed by moulins** 2019-12-28 23:41 UTC
