### ISSUE TITLE
Amidst v4-6-beta6 "Unable to Create World" crash

### ISSUE THREAD

**Issue by ariosos** [toolbox4minecraft/amidst#491] opened 2019-05-15 15:51 UTC
I am using a vanilla profile for Minecraft 1.13.2.

- Opened up admist, selected a vanilla profile.
- File-> New From Seed: 7401940892151137080
- Selected World Type default

BTW, the Beta5 download does work with 1.13.2. 

(unfortunately, I don't see any text-based output, so I can only paste the screenshot)
![image](https://user-images.githubusercontent.com/7917753/57789626-4ce40880-7707-11e9-92eb-0a15a208c28f.png)

**Comment by moulins** [comment] 2019-05-15 18:53
Closing as duplicate of #487.

**Closed by moulins** 2019-05-15 18:53 UTC

**Comment by BigAlanM** [comment] 2019-06-13 21:06
I'm having the same problem.   4.3 beta 6 seems to work with all versions back to 1.6.4 and probably earlier but will not work with 1.13.2 in any way.  Ctrl-R, Ctrl-N, or File> Open save game...
I does, however, work with 1.14.2.
