### ISSUE TITLE
amidst is unable to create local minecraft interface

### ISSUE THREAD

**Issue by essickmango** [toolbox4minecraft/amidst#415] opened 2018-07-25 08:23 UTC
Hello. I'm using Linux with java 8. When I select my profile, it gives me this crash report:

[info] Amidst v4.3-beta3
[info] Current system time: 2018-07-25 10:12:09.568
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.15.0-29-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_171'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default

...

[info] Finished loading libraries.
[info] Unable to recognise Minecraft Version with the magic string "adrxquaom[Ltc;vo[J[[Jvkuwuubvavhxaprpvccipopp".
[info] Reading 1.13.jar
[info] Jar load complete.
[info] Searching for classes...
[error] amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceCreationException: unable to create local minecraft interface
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:47)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.create(LocalMinecraftInterface.java:20)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:25)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:17)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:102)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: cannot find a real class matching the symbolic class IntCache
	at amidst.clazz.symbolic.declaration.SymbolicClassDeclaration.handleNoMatch(SymbolicClassDeclaration.java:64)
	at amidst.clazz.translator.ClassTranslator.addResult(ClassTranslator.java:56)
	at amidst.clazz.translator.ClassTranslator.translate(ClassTranslator.java:43)
	at amidst.clazz.Classes.createSymbolicClassMap(Classes.java:39)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:33)
	... 8 more

If there is a way to log this into a file, I will do this.
Thanks in advance!

edit:
I get the same Error using the exe on Windows with java 8

**Comment by essickmango** [comment] 2018-07-26 09:37
Well, I realised the support only reaches 1.12.2, I was trying to load an 1.13 profile

**Comment by moulins** [comment] 2018-07-26 19:11
Duplicate of #395.

**Closed by moulins** 2018-07-26 19:12 UTC
