### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by lajawi** [toolbox4minecraft/amidst#903] opened 2020-09-30 16:46 UTC
Where can I open the nether?

**Comment by BRBosley** [comment] 2020-10-02 20:28
Currently there is no support for nether biome generation. The best you can do is be patient with the developers of amidst, since they have spent years making this program, and at the same time make sure they have time to live their life. It is better to be respectful to them, and be thankful that they take some time (Not all though) from their lives to make this program.

You should also check open and closed bug reports before you send a 6 word question which is meaningless. There are already 2 answers, which you could have gotten your answer from:
[691](https://github.com/toolbox4minecraft/amidst/issues/691)
[692](https://github.com/toolbox4minecraft/amidst/issues/692)
So, now you have an Answer, so have a good rest of your day.

**Comment by moulins** [comment] 2020-10-06 09:13
Duplicate of #692, closing.

**Closed by moulins** 2020-10-06 09:13 UTC
