### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by wizardglick** [toolbox4minecraft/amidst#572] opened 2019-12-12 02:40 UTC
First time I have used this. Upgraded to MC 1.15 yesterday.

[info] Amidst v4.3
[info] Current system time: 2019-12-11 21:33:03.993
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_161'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Jimmy\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'Latest version' with versionId '1.15'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library com.mojang:javabridge:1.0.22 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.17 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[info] Found library com.mojang:datafixerupper:2.0.24 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/Jimmy/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Unable to recognise Minecraft Version with the magic string "bjxcrmajpaiixurwzo[Jzkyqyocrbguabbtacrgtdcrzcrysxsyabj".
[info] Reading 1.15.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class OverworldGenSettings: cbw
[info] Found class LayerUtil: cph
[info] Found class RegistryKey: sm
[info] Found class WorldType: bka
[info] Found class Biome: bkq
[info] Found class Bootstrap: so
[info] Found class GenLayer: drc
[info] Found class Registry: gb
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method drc.a(int, int, int, int, @Biome) -> GenLayer.getBiomeData
[info] Classes loaded.
[info] Minecraft load complete.
[info] Not writing to seed history file, because it does not exist: history.txt
[info] Creating world with seed '1944938274' and type 'Default'
[info] Using the following generator options: 
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.ClassCastException: cpg cannot be cast to [Ljava.lang.Object;
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:212)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.createWorld(LoggingMinecraftInterface.java:26)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:116)
	at amidst.mojangapi.world.WorldBuilder.fromSaveGame(WorldBuilder.java:90)
	at amidst.mojangapi.RunningLauncherProfile.createWorldFromSaveGame(RunningLauncherProfile.java:87)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:78)
	at amidst.gui.main.Actions.openSaveGame(Actions.java:90)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:133)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by PuzzleSecretary** [comment] 2019-12-12 11:11
I got a very similar-looking crash running it in Win7 instead of Win10, also in 1.15.  Can confirm it was working in 1.14.4, so unsurprisingly it seems like 1.15 has thrown things for a loop.

[info] Amidst v4.3
[info] Current system time: 2019-12-12 03:06:44.215
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_191'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Pteryx\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'Latest version' with versionId '1.15'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library com.mojang:javabridge:1.0.22 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.17 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[info] Found library com.mojang:datafixerupper:2.0.24 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/Pteryx/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Unable to recognise Minecraft Version with the magic string "bjxcrmajpaiixurwzo[Jzkyqyocrbguabbtacrgtdcrzcrysxsyabj".
[info] Reading 1.15.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class Biome: bkq
[info] Found class Bootstrap: so
[info] Found class LayerUtil: cph
[info] Found class OverworldGenSettings: cbw
[info] Found class RegistryKey: sm
[info] Found class Registry: gb
[info] Found class WorldType: bka
[info] Found class GenLayer: drc
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method drc.a(int, int, int, int, @Biome) -> GenLayer.getBiomeData
[info] Classes loaded.
[info] Minecraft load complete.
[info] Not writing to seed history file, because it does not exist: history.txt
[info] Creating world with seed '-6941179871680630381' and type 'Default'
[info] Using the following generator options: 
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.ClassCastException: cpg cannot be cast to [Ljava.lang.Object;
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:212)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.createWorld(LoggingMinecraftInterface.java:26)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:116)
	at amidst.mojangapi.world.WorldBuilder.fromSaveGame(WorldBuilder.java:90)
	at amidst.mojangapi.RunningLauncherProfile.createWorldFromSaveGame(RunningLauncherProfile.java:87)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:78)
	at amidst.gui.main.Actions.openSaveGame(Actions.java:90)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:133)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by moulins** [comment] 2019-12-12 15:59
Duplicate of #538; this is fixed in the latest release (v4.4-beta1)

**Closed by moulins** 2019-12-12 15:59 UTC

**Comment by wizardglick** [comment] 2019-12-12 19:21
Yes, I did  get 4.4.beta1 and everything was shiny. Thanks.
