### ISSUE TITLE
Crash with amidst version 4.2 opening mc 1.11.2

### ISSUE THREAD

**Issue by iTecAI** [toolbox4minecraft/amidst#383] opened 2018-03-31 15:43 UTC
I am trying to use amidst to view a world, but it crashes when attempting to use the mc 1.11.2 profile (none of the other profiles work either, but they don't crash.
OS: Windows 7
Crash: 
```
[info] Amidst v4.2
[info] Current system time: 2018-03-31 11:41:15.003
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_151'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Matteo\AppData\Roaming\.minecraft', libraries: 'C:\Users\Matteo\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] There are no updates available.
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] using minecraft launcher profile '' with versionId '1.12.2'
[info] Loading libraries.
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.19\realms-1.10.19.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3-natives-windows.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3-natives-windows.jar
[info] Skipping library: ca.weblite:java-objc-bridge:1.0.0
[info] Skipping library: ca.weblite:java-objc-bridge:1.0.0
[info] Unable to recognise Minecraft Version with the magic string "ulrlozmtry[Loo;pl[J[[Jph".
[info] Reading 1.12.2.jar
[error] amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceCreationException: unable to create local minecraft interface
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:50)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:100)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: amidst.clazz.real.JarFileParsingException: Error extracting jar data.
	at amidst.clazz.real.RealClasses.readRealClassesFromJarFile(RealClasses.java:37)
	at amidst.clazz.real.RealClasses.fromJarFile(RealClasses.java:23)
	at amidst.clazz.Classes.createSymbolicClassMap(Classes.java:35)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:35)
	... 7 more
Caused by: amidst.clazz.real.RealClassCreationException: unable to create real class for the class: cgw
	at amidst.clazz.real.RealClassBuilder.construct(RealClassBuilder.java:18)
	at amidst.clazz.real.RealClasses.readRealClass(RealClasses.java:72)
	at amidst.clazz.real.RealClasses.readJarFileEntry(RealClasses.java:58)
	at amidst.clazz.real.RealClasses.readJarFile(RealClasses.java:45)
	at amidst.clazz.real.RealClasses.readRealClassesFromJarFile(RealClasses.java:33)
	... 10 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(Unknown Source)
	at amidst.clazz.real.RealClassBuilder.readFields(RealClassBuilder.java:223)
	at amidst.clazz.real.RealClassBuilder.doConstruct(RealClassBuilder.java:47)
	at amidst.clazz.real.RealClassBuilder.construct(RealClassBuilder.java:16)
	... 14 more

[info] using minecraft launcher profile '1.11.2' with versionId '1.11.2'
[info] Loading libraries.
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6
[info] Skipping library: com.mojang:netty:1.6
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0
[info] Skipping library: net.java.dev.jna:jna:3.4.0
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6
[info] Skipping library: net.sf.jopt-simple:jopt-simple:4.6
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final
[info] Skipping library: io.netty:netty-all:4.0.23.Final
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0
[info] Skipping library: com.google.guava:guava:17.0
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2
[info] Skipping library: org.apache.commons:commons-lang3:3.3.2
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4
[info] Skipping library: commons-io:commons-io:2.4
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9
[info] Skipping library: commons-codec:commons-codec:1.9
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4
[info] Skipping library: com.google.code.gson:gson:2.2.4
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.24
[info] Skipping library: com.mojang:authlib:1.5.24
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.16
[info] Skipping library: com.mojang:realms:1.10.16
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang
[info] Skipping library: it.unimi.dsi:fastutil:7.0.12_mojang
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9
[info] Skipping library: org.apache.logging.log4j:log4j-api:2.0-beta9
[warning] Failed attempt to load library at: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9
[info] Skipping library: org.apache.logging.log4j:log4j-core:2.0-beta9
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: C:\Users\Matteo\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-6,1,main]
[crash] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ListenableFuture
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:142)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:134)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:129)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:33)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:100)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

**Comment by moulins** [comment] 2019-03-02 18:22
Can't reproduce on current `master` version (15953d62), closing.

**Closed by moulins** 2019-03-02 18:22 UTC
Labels: crash
