### ISSUE TITLE
BUG 1.14 Stronghold location wrong

### ISSUE THREAD

**Issue by lams2135** [toolbox4minecraft/amidst#492] opened 2019-05-19 11:54 UTC
Version Amidst v4.3-beta6
MC Version 1.14 (vanilla server)

Some of the Stronghold coordinate given by amidst is not really generated by vanilla server.
I guess its similar issue to https://github.com/toolbox4minecraft/amidst/issues/453 but not fixed in v4.3-beta6(1.14).
Example seed: 5025083063634127729;
Example stronghold coordinate: [-1376, -656] (not really generated)

Btw, I tested more then 10 stronghold coordinates given by amidst, but only about half of them are correct.

**Comment by moulins** [comment] 2019-05-19 13:15
Issue confirmed; I'll close this as a duplicate of #453.

**Closed by moulins** 2019-05-19 13:15 UTC
Labels: duplicate
