### ISSUE TITLE
Can't paste seed (mac/jar)

### ISSUE THREAD

**Issue by breon** [toolbox4minecraft/amidst#781] opened 2020-06-26 16:22 UTC
### Preconditions
* v4.5-beta1 installed
* Seed copied to clipboard

### Steps
* Launch Amidst
* File > New From Seed
* Click in text field
* Press CMD+V 

### Expected
* Seed pasted into text field

### Actual
* Nothing happens

<img width="611" alt="Screen Shot 2020-06-26 at 11 17 08 AM" src="https://user-images.githubusercontent.com/183894/85878707-c40b1d80-b79e-11ea-9d08-dfbf81b50b35.png">

**Comment by moulins** [comment] 2020-06-30 00:10
Can you provide the OS and Java version? (you can get them in **Help > Display Log Messages**)

Also, does the issue occurs when using the bundled app?

**Comment by breon** [comment] 2020-06-30 15:51
```[info] Amidst v4.5-beta1
[info] Current system time: 2020-06-30 10:45:31.529
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.15.5'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '1.8.0_112'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'```

Not sure what you mean by bundled app. Also, it appears to be a duplicate of #695. When using "System look and feel" pasting a seed works. With "Default look and feel" it doesn't.

**Comment by burgerguy** [comment] 2020-07-02 16:18
@moulins We should probably make the system LAF default so issues like this don’t happen. Many people would also prefer how it looks over the built in LAF that comes with java.

**Comment by moulins** [comment] 2020-07-18 10:12
Closing as duplicate of #695.

**Closed by moulins** 2020-07-18 10:12 UTC
Labels: waiting-for-answer
