### ISSUE TITLE
Mob Spawner Icon with specific spawner type

### ISSUE THREAD

**Issue by jonathanjeshua** [toolbox4minecraft/amidst#563] opened 2019-10-28 11:23 UTC
implement spawner please :((

**Comment by machinesmith42** [comment] 2019-10-28 18:51
Spwaners cannot be found by amidst

**Comment by magicus** [comment] 2019-10-29 07:53
It should be technically possible. Spawners are quickly and (as far as I tested) correctly located by https://chunkbase.com/apps/dungeon-finder. I realize that this implementation does not utilize the Mojang code the way Amidst does, but if it's hard to locate spawners using the Mojang code, maybe Amidst could reimplement the same algoritm as chunkbase is using. 

I agree that it would be a very useful addition to Amidst to have mob spawners shown. It's almost a one-stop solution for all Minecraft map exploration needs.

**Comment by jonathanjeshua** [comment] 2019-10-31 02:37
I've tried dungeon finder but it does not work at all. Amidst is one of my
most favorite tools in minecraft because it is almost a complete package
for me.

**Comment by moulins** [comment] 2019-11-10 22:12
Duplicate of #57.

I don't know what algorithm ChunkBase uses to find dungeons locations, but you need to have access to the fully generated chunk to know where dungeons will generate. As Amidst only calculate the biome map, and not the full chunks (generating thousands of chunks isn't feasible in a reasonable amount of time), dungeons positions are out-of-scope for Amidst.

**Closed by moulins** 2019-11-10 22:12 UTC

**Comment by jonathanjeshua** [comment] 2020-01-31 03:17
Hey,

I just signed the petition "philippine president: Stop the Wuhan virus from
entering Philippines!!" and wanted to see if you could help by adding your
name.

Our goal is to reach 50,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/TtXKSTR95G

Thanks!
Jonathan Jeshua
