### ISSUE TITLE
amidst failiure to start

### ISSUE THREAD

**Issue by withoutstrings** [toolbox4minecraft/amidst#345] opened 2017-09-04 23:16 UTC
![screenshot from 2017-09-04 18-10-07](https://user-images.githubusercontent.com/26998615/30039859-5eeaffcc-919c-11e7-9391-a3990a5cc8a5.png)

ubuntu 16.04
java version "1.8.0_144"
minecraft 1.12.1
amidst 4-2
 when launching amidst, the profile selector comes up, i click amidst profile, get the attached error output and the programme fails to load.

**Comment by stefandollase** [comment] 2018-04-08 09:49
This is a duplicate of #378

**Closed by stefandollase** 2018-04-08 09:49 UTC
Labels: bug, duplicate

**Comment by withoutstrings** [comment] 2018-04-08 17:57
Seriously I post a year ago asking for help and now you close it as a
duplicate of something 2 weeks ago after providing me no assistance? Thanks
for your incredible service.

**Comment by stefandollase** [comment] 2018-04-08 18:43
Closing as a duplicate of something else does *not* mean that I think the issue is invalid or something. It just helps to keep the issue tracker organized if there is only one issue for every bug. Does it really matter which of the duplicates is kept open?

Also, I just published a new pre-release, which should work with Minecraft 1.12.2, but not with current snapshots. You can try it right now and provide feedback if you like to.

I understand that you are angry because it did took me half a year to respond. However, yelling at the developer of a free and open source software project usually does not encourage them to put more time and effort into the project. But I know, it is so much work to use a free and open source software product which does not even cost you anything. The developers should thank you for using it, right?

**Comment by withoutstrings** [comment] 2018-04-09 00:09
Sigh. You could at least start at the beginning not the end. To be honest I
thought your project had reached end of life. I'm glad to see you are back
at it. Thank you for that.
