### ISSUE TITLE
Displayed profile order seems to mismatch internal profile order

### ISSUE THREAD

**Issue by TheRealWormbo** [toolbox4minecraft/amidst#784] opened 2020-06-27 12:58 UTC
Amidst: 4.5-beta1
Operating system: Linux Mint 19.3 Cinnamon
Java runtime: OpenJDK 11.0.7

The initial profile selection list is displayed in a different order than what profiles are actually in each line. When I load Amidst 4.5b1, I get presented with this list:
![Amidst profile list initial](https://user-images.githubusercontent.com/7620864/85922604-f8f1a000-b884-11ea-8e8d-9680d271229f.png)
When I scroll through the entries with the up/down arrows, it selects them in a weird, seemingly random order and picking one (non-mod) entry isn't guaranteed to launch with that profile.

When I select File -> Switch Profile, I may be presented with this ordering instead, which seems to actually be correct:
![Amidst profile list switch](https://user-images.githubusercontent.com/7620864/85922606-fbec9080-b884-11ea-9508-37b97a3a091a.png)
Picking a particular profile this time seems to actually load that one.

Whether or not the profile list is in the correct order appears to be random. If it's off, it will always be in the same wrong order, as shown in the initial screenshot.

**Comment by TheRealWormbo** [comment] 2020-06-27 13:48
I just realized this is probably a duplicate of #777. Log for launching and clicking on the second profile (displayed as "Latest Release"), which turned out to be the 1.15.2 profile instead:

> [info] Amidst v4.5-beta1
> [info] Current system time: 2020-06-27 15:45:03.736
> [info] System.getProperty("os.name") == 'Linux'
> [info] System.getProperty("os.version") == '5.3.0-61-generic'
> [info] System.getProperty("os.arch") == 'amd64'
> [info] System.getProperty("java.version") == '11.0.7'
> [info] System.getProperty("java.vendor") == 'Ubuntu'
> [info] System.getProperty("sun.arch.data.model") == '64'
> [info] Not using OpenGL.
> [info] Biome profile activated: Default
> [info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
> [info] using '.minecraft' directory at: '/home/wormbo/.minecraft'
> [info] using biome profiles at: 'biome'
> [info] Starting to download remote version list.
> [info] Scanning for profiles.
> [info] Successfully loaded profile list.
> [info] There are no updates available.
> [info] Successfully loaded remote version list.
> [info] using minecraft launcher profile '1.15.2' with versionId '1.15.2'
> [info] Loading libraries.
> [info] Found library com.mojang:patchy:1.1 at file:/home/wormbo/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
> [info] Found library oshi-project:oshi-core:1.1 at file:/home/wormbo/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
> [info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/wormbo/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
> [info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/wormbo/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
> [info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/home/wormbo/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
> [info] Found library com.mojang:javabridge:1.0.22 at file:/home/wormbo/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
> [info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/wormbo/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
> [info] Found library io.netty:netty-all:4.1.25.Final at file:/home/wormbo/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
> [info] Found library com.google.guava:guava:21.0 at file:/home/wormbo/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
> [info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/wormbo/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
> [info] Found library commons-io:commons-io:2.5 at file:/home/wormbo/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
> [info] Found library commons-codec:commons-codec:1.10 at file:/home/wormbo/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
> [info] Found library net.java.jinput:jinput:2.0.5 at file:/home/wormbo/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
> [info] Found library net.java.jutils:jutils:1.0.0 at file:/home/wormbo/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
> [info] Found library com.mojang:brigadier:1.0.17 at file:/home/wormbo/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
> [info] Found library com.mojang:datafixerupper:2.0.24 at file:/home/wormbo/.minecraft/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
> [info] Found library com.google.code.gson:gson:2.8.0 at file:/home/wormbo/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
> [info] Found library com.mojang:authlib:1.5.25 at file:/home/wormbo/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
> [info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/wormbo/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
> [info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/wormbo/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
> [info] Found library commons-logging:commons-logging:1.1.3 at file:/home/wormbo/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
> [info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/wormbo/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
> [info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/home/wormbo/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
> [info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/wormbo/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
> [info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/wormbo/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
> [info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
> [info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
> [info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
> [info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
> [info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
> [info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
> [info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
> [info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
> [info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
> [info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
> [info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
> [info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
> [info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
> [info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
> [info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
> [info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/wormbo/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
> [info] Found library com.mojang:text2speech:1.11.3 at file:/home/wormbo/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
> [info] Found library com.mojang:text2speech:1.11.3 at file:/home/wormbo/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
> [info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
> [info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
> [info] Finished loading libraries.
> [info] Recognised Minecraft Version 1.15.2 with the magic string "bkacrpajsaikxurwzo[Jzkyqyocrbgxabbtacrjtdcsccsbsxsyabj".
> [info] Reading 1.15.2.jar
> [info] Jar load complete.
> [info] Searching for classes...
> [info] Found class WorldData: crm
> [info] Found class GameType: bjt
> [info] Found class Registry: gb
> [info] Found class WorldSettings: bka
> [info] Found class NoiseBiomeProvider: bkv$a
> [info] Found class Util: t
> [info] Found class RegistryKey: sm
> [info] Found class OverworldBiomeZoomer: bmb
> [info] Found class WorldType: bkd
> [info] Found class Biome: bkt
> [info] Class search complete.
> [info] Loading classes...
> [info] unable to find the real class constructor crm.<init>(@WorldSettings) -> WorldData.<init2>
> [info] Classes loaded.
> [info] Minecraft load complete.
> 
>

**Comment by moulins** [comment] 2020-06-29 23:43
This is not actually a duplicate of #777 ;)

However, I can't reproduce on my machine (also a Linux Mint); I'll have to investigate more.

**Closed** 2020-06-30 01:24 UTC
Labels: bug
