### ISSUE TITLE
Crash when loading a world 

### ISSUE THREAD

**Issue by DNRSS** [toolbox4minecraft/amidst#444] opened 2018-08-30 22:29 UTC
Program generates infinite error messages when loading a world, both from save and from seed. Error log attached (large) 
[2018-08-30-2.log](https://github.com/toolbox4minecraft/amidst/files/2338152/2018-08-30-2.log)

**Comment by moulins** [comment] 2018-08-31 00:34
Closing as duplicate of #432.

**Closed by moulins** 2018-08-31 00:34 UTC
