### ISSUE TITLE
Suggestion: Add spawn chunks layer

### ISSUE THREAD

**Issue by EduMenges** [toolbox4minecraft/amidst#708] opened 2020-03-06 10:52 UTC
There's already a layer for the player spawn location and a layer for slime chunks, With a spawn chunks layer it would be easier to see them and to see which biomes are in the spawn.

**Comment by moulins** [comment] 2020-03-06 13:05
Duplicate of #213; closing.

**Closed by moulins** 2020-03-06 13:05 UTC
Labels: duplicate

**Comment by EduMenges** [comment] 2020-03-06 13:47
Another one to the list I guess.
