### ISSUE TITLE
Keep Getting This Eroor and it wont show the map

### ISSUE THREAD

**Issue by EclipseWasTaken** [toolbox4minecraft/amidst#489] opened 2019-05-11 13:53 UTC
[info] Amidst v4.3-beta6
[info] Current system time: 2019-05-11 14:50:55.499
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_201'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\burno\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile '' with versionId '1.13.2'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.14 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar
[info] Found library com.mojang:datafixerupper:1.0.19 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/mojang/datafixerupper/1.0.19/datafixerupper-1.0.19.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library com.mojang:realms:1.13.9 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/mojang/realms/1.13.9/realms-1.13.9.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-windows.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-windows.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/C:/Users/burno/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Recognised Minecraft Version 1.13.2 with the magic string "aduxrubomvp[Jvluxuvbvavlxbprpvcctpopp".
[info] Reading 1.13.2.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class WorldType: ayg
[info] Found class GenLayer: bzx
[info] Found class RegistryKey: pc
[info] Found class Registry: fc
[info] Found class OverworldGenSettings: bou
[info] Found class Bootstrap: pf
[info] Found class LayerUtil: bzy
[info] Found class Biome: ayu
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method bzx.a(int, int, int, int) -> GenLayer.getBiomeData2
[info] Classes loaded.
[info] Minecraft load complete.
[info] Not writing to seed history file, because it does not exist: history.txt
[info] Creating world with seed '-6901931220884427379' and type 'Default'
[info] Using the following generator options: 
[warning] amidst.mojangapi.minecraftinterface.MinecraftInterfaceException: unable to create world
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:228)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.createWorld(LoggingMinecraftInterface.java:26)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:115)
	at amidst.mojangapi.world.WorldBuilder.from(WorldBuilder.java:65)
	at amidst.mojangapi.RunningLauncherProfile.createWorld(RunningLauncherProfile.java:69)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:67)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:77)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:64)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:133)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at amidst.clazz.symbolic.SymbolicConstructor.newInstance(SymbolicConstructor.java:37)
	at amidst.clazz.symbolic.SymbolicConstructor.call(SymbolicConstructor.java:25)
	at amidst.clazz.symbolic.SymbolicClass.callConstructor(SymbolicClass.java:79)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getGenSettings(LocalMinecraftInterface.java:267)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:216)
	... 46 more
Caused by: java.lang.ExceptionInInitializerError
	at bol.<init>(SourceFile:24)
	at bou.<init>(SourceFile:3)
	... 55 more
Caused by: java.lang.RuntimeException: Accessed Blocks before Bootstrap!
	at bct.<clinit>(SourceFile:13)
	... 57 more

**Comment by moulins** [comment] 2019-05-11 14:16
Closing as duplicate of #487.

**Closed by moulins** 2019-05-11 14:16 UTC
