### ISSUE TITLE
 amidst-v4-3-beta4 unable to load map on MacOS

### ISSUE THREAD

**Issue by AdriaanRenting** [toolbox4minecraft/amidst#436] opened 2018-08-24 19:44 UTC
I'm running MacOS High Sierra 10.13.6
I'm running java version 1.8.0_77

I tried using amidst-v4-3-beta4.zip

I can start the program.
It allows me to select a game version (1.13.1).
I get an empty map.
When I either try to open a save or give it a seed or random seed, the program starts spamming error screens. I think there is something in it, but it is spamming so many and so fast, that it basically constantly flickers and mostly seems to show an empty window as it tries to render what must be several error screens per second.

**Comment by AdriaanRenting** [comment] 2018-08-24 19:45
![screen shot 2018-08-24 at 21 43 42](https://user-images.githubusercontent.com/20068104/44604680-fc2e2780-a7e6-11e8-917c-a978c7920032.png)

**Comment by AdriaanRenting** [comment] 2018-08-24 19:47
I have to hard kill it from another screen as the computer becomes unresponsive after a while.

**Comment by DaMonkE** [comment] 2018-08-24 20:15
I am having this issue on windows 10 as well

**Comment by moulins** [comment] 2018-08-24 20:42
Closing as duplicate of #432.

**Closed by moulins** 2018-08-24 20:42 UTC
