### ISSUE TITLE
Add a list of woodland Mansions

### ISSUE THREAD

**Issue by Ree11** [toolbox4minecraft/amidst#358] opened 2017-12-21 02:10 UTC
Shouldn't be to hard and would really make this app perfect for finding structures and seeds.

just like the list of end portals that can be showed by going to world and clicking stronghold have the option to jump to woodland mansions would be so nice

**Comment by stefandollase** [comment] 2018-04-08 09:35
This is a duplicate of #233

**Closed by stefandollase** 2018-04-08 09:35 UTC
Labels: duplicate, feature
