### ISSUE TITLE
Minecraft regions

### ISSUE THREAD

**Issue by zbkingCZ** [toolbox4minecraft/amidst#387] opened 2018-04-15 06:17 UTC
Add information about Minecraft regions. I think it's useful information for map creators and server administrators.

**Comment by mkalb** [comment] 2018-04-17 09:58
https://dinnerbone.com/minecraft/tools/coordinates/

**Comment by zbkingCZ** [comment] 2018-05-14 10:32
Thank you for your answer. Yes, I know the website. That's the reason why this information could be in the Amidst. Now I have to switch between tree applications, Amidst to get coordinates, web browser to get region file name and file manager.

**Comment by moulins** [comment] 2018-05-14 18:40
One way to avoid switching back and forth is to use the grid. Each region is 512x512 blocks, and the grid is 512x512, 1024x1024 or 1536x1536, depending on the zoom level, so you can easily count the regions manually.

**Comment by moulins** [comment] 2018-06-24 18:18
Duplicate of #321.

**Closed by moulins** 2018-06-24 18:18 UTC
Labels: duplicate, feature
