### ISSUE TITLE
Nether Biome Issues

### ISSUE THREAD

**Issue by pandapants200** [toolbox4minecraft/amidst#914] opened 2020-11-16 23:07 UTC
I am not sure if I am doing something wrong or if the feature is not yet supported but I can't view the nether biomes in the latest version. Is there a selector for switching to the nether dimension?

**Comment by guitaristtom** [comment] 2020-11-21 10:13
Looks like there isn't support for it quite yet, according to the release notes for a pre-release of this program.

But I do personally hope they add support for it soon. It would really benefit myself and a couple friends.

**Comment by moulins** [comment] 2020-12-06 02:00
Nether biomes are not implemented yet. The internal code is there, but I still need to figure how to show it in the GUI.

Duplicate of #692.

**Closed by moulins** 2020-12-06 02:00 UTC
