### ISSUE TITLE
No me deja jugar con optifine

### ISSUE THREAD

**Issue by Francisco19** [toolbox4minecraft/amidst#175] opened 2016-05-26 20:05 UTC
Mi caso es que cuando me dice que elija mi perfil elijo el de optifine y me dice que a ocurrido un error entonces cambio a forge y me dice lo mismo y lo pongo en un perfil cualquiera que no le pongo ni forge ni optifine y si me deja pero yo quiero jugar con optifine ya que me quita lag. Espero respuesta gracias

**Comment by stefandollase** [comment] 2016-05-26 20:20
I used google translate to read the text and my understanding is that you receive an error when you try to run Amidst with an Optifine and/or Forge profile. This is currently the expected behavior. I hope you understand english:

I close this as invalid, because Amidst does not support modded Minecraft.

You can still use Amidst with an unmodded Minecraft profile. To do so, please create a new profile with the Minecraft launcher. Call it something like "Amidst" and use that when Amidst asks you for a profile. Make sure to select the correct Minecraft version when creating the new profile.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)

For more information, please read the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)

Optifine might be supported in a future version, see #110

**Closed by stefandollase** 2016-05-26 20:20 UTC
Labels: bug, invalid
