### ISSUE TITLE
Error Spam upon opening world

### ISSUE THREAD

**Issue by L3thal1ty** [toolbox4minecraft/amidst#440] opened 2018-08-27 19:07 UTC
I downloaded the new beta version (.exe version) and loaded my level.dat file only to get a massive influx of overlapping error messages. There were 140+ error windows that opened up, most of which were solid white, and Amidst started to suck up over 1.5gb of RAM, and it would just kind of halt, opening a new error window every minute or so. This went on for about 2-3 minutes before I gave up and ended the process. I tried just loading my seed, thinking it may be an issue with my level.dat. This had mostly the same result, except that it actually crashed after about 10 seconds of loading error windows instead of just continuing. I managed to screenshot one of the flashing error windows, I will add a picture below. I don't know if there is a log that gets saved, but if there is, please tell me where to find it, and I will gladly share it.

[Error Window](https://cdn.discordapp.com/attachments/281595558731186176/483710758719324171/unknown.png)

[RAM Usage](https://cdn.discordapp.com/attachments/281595558731186176/483710810288422932/unknown.png)

**Comment by moulins** [comment] 2018-08-27 19:27
Duplicate of #432.

**Closed by moulins** 2018-08-27 19:27 UTC

**Comment by L3thal1ty** [comment] 2018-08-27 19:44
Thanks for pointing me to another instance of the same issue, but I noticed that the issue you linked to was also closed, with no further input. Was that the extent of the issue, just "we should do something about it"?
