### ISSUE TITLE
Woodland Mansion Icon

### ISSUE THREAD

**Issue by Athlonx8** [toolbox4minecraft/amidst#375] opened 2018-03-15 11:48 UTC
I would like to have the ability to actually see where woodland mansion is using amidst as it is not yet possible. If you could make that happen you would help alot of players that are using your program to find locations that way. Thank you.

**Comment by stefandollase** [comment] 2018-04-08 09:34
This is a duplicate of #233

**Closed by stefandollase** 2018-04-08 09:34 UTC
Labels: duplicate, feature
