### ISSUE TITLE
Error selecting profile

### ISSUE THREAD

**Issue by Narrrz** [toolbox4minecraft/amidst#350] opened 2017-10-08 04:35 UTC
![iamerror](https://user-images.githubusercontent.com/32607101/31313949-0d9e7ec8-ac4f-11e7-999b-9ae720024a14.png)

I get this issue when clicking on a profile. Neither of the available profiles have any name associated with them.

**Comment by stefandollase** [comment] 2018-04-08 09:55
This is a duplicate of #378

**Closed by stefandollase** 2018-04-08 09:55 UTC
Labels: bug, duplicate
