### ISSUE TITLE
First impressions of 4.0 beta versions

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#12] opened 2016-01-05 16:31 UTC
I no longer admit to being a programmer as my knowledge is considerably out of date.
I am, however, an avid user and proponent of Amidst and AmidstExporter.

That being said there are two things that stood out for me when I ran Amidst v4.0 beta1.
First is Beta1 not having the feature of displaying Mineshafts (Ctrl+9) of AmidstExporter. 
(Which moves Spawn location to Ctrl+0)
I assume that the code for that will be merged at some point.

The other is more irking. AmidstExporter maps Nether Fortresses at their Overworld equivalent locations. ie where you would have to place a portal in the Overworld to emerge in (or very near) that fortress.  Beta 1 doesn't do this. Instead it maps the Nether Fortresses on the Overworld map with their Nether coordinates which is quite confusing (in my way of thinking).  AmidstExporter's way to mitigate the coordinate difference is to display BOTH sets of numbers when a Fortress Icon is clicked.

Also the fortress coordinates displayed aren't the same between the two programs.
AE appears to display more precise values and Beta1 displays a corner of a Chunk. ie the coordinates are exact multiples of 16.

Something that I DO like is the ability to change Minecraft profiles without having to close the program and restart it. (Which I normally don't do anyway. I just start a second instance of the program.)

Question: How is "Check for Updates" going to be handled? Or is it?

**Comment by stefandollase** [comment] 2016-01-05 21:54
Thanks for your feedback. As you already guessed, we aim to merge these features of AmidstExporter into this repository. I will also look into the difference for the nether fortress coordinates.

The profile switching is a feature that became possible after many refactorings. Good to hear, that you like it.

The beta1 still uses the same update mechanism as the original Amidst. However, I reworked the update mechanism since the release, so the next release will use the new update mechanism, which is based on the Github Pages service. This is to make the update document accessible for all collaborators. I guess/hope skiphs will post a new update document to the old location, as soon as we have a stable release, so all current users will be informed about the new version. The old update mechanism also offers the ability to publish any url for the new version, so it is possible to point the users to this repository.

**Comment by stefandollase** [comment] 2016-01-05 21:55
Just another question: Did you experience any problems/issues/bugs with the beta1? Which operating system do you use?

**Comment by BigAlanM** [comment] 2016-01-06 21:02
So far no problems. But I haven't spent much time with it.
I'm running Windows 10 with 64bit Java.
Also I tested both the .jar and the .exe. The seemed to behave the same.
I had quit using .exe files when Amidst.exe started crashing on me and the .jar worked.
Because I'm in the habit of using the .jar files I use a batch file to run it using a start command so as to kill the batch file when Java executes the .jar.

IE: 
start javaw.exe -jar "<my path >\amidst-v40-beta1.jar"

BTW Windows REALLY doesn't like having more than one period in a file name.

**Comment by BigAlanM** [comment] 2016-01-06 21:31
Just downloaded Beta2 and ran the .jar.
I definitely like that the Highlight Biome function doesn't reset after displaying a new seed!
I was using special color .json files to do specialty searches for specific biomes near spawn.

I would probably confuse newer Minecrafters less if Hell were removed from the list or at least changed to "Nether".  Now that I think of it, it doesn't need to be in the list, does it?

I like the fact that active layers are indicated in the Layers menu.  Nice!

History.txt doesn't update.
OBTW - I wrote a batch file to rename history.txt with the current date in the name and then copy a blank file to history.txt.  

Should there be a way to set the max zoom limit? With a warning perhaps.

I like that the program remembers where to save screen captures. Should Settings be able to set this location?

**Comment by stefandollase** [comment] 2016-01-07 16:28
Thanks for the information about your platform. This means, that it did run at least once on every platform :-)

Regarding the issue with more than one period in the file name: I have to admit, I did not even think about this. I cannot believe this is still an issue ... but I do not want to start flaming. I guess, I will change this in the next release.

Regarding the biome name: I just looked into it, until Minecraft 1.8, the official biome names were Sky and Hell for the End biome and the Nether biome (this is what was displayed in the F3 screen). Since 1.8, they renamed Sky to The End, but they kept Hell. I do not think, they did this by accident, so I guess we will stick with the official biome names of the latest release, which would be The End and Hell. If users are confused by this, then they are at least equally confused when they look at the biome name in the F3 screen. To get to the point: I think it causes more confusion to see different biome names in Amidst and Minecraft than to see not well known biome names. For Amidst, most users wont see the biome name for the nether anyway, since we do not display the Nether dimension, but the Hell biome is only generated in the Nether. So, the only place where the user sees the biome name is in the biome color profile json file. I suppose, this is not the majority of the users. Maybe, your suggestions to just remove the hell biome from the biome list is a good one. I just double checked, you cannot even generate the hell biome in the Overworld with the custom terrain generator, so it should be save to remove the Hell biome.

The seed history is deactivated by default. To activate it, you can use the `-history <file>` command line option. Here, you can also specify the file name, so you do not need to rename the file afterwards.

I guess, I will add the seed text to the history file, if the seed was created from a text, or do you see any issues with this? It will appear after the numeric seed.

Just to be sure, you know the setting to restrict the zoom, but you want to be able to set a custom maximum zoom level? I cannot think of any common use case for this. What is your use case?

And again, just to be sure: The beta2 remembers the location where to save a screenshot? So, you take one screenshot, then a second and the second time the directory of the first time is pre-selected? I ask, because this is not the behavior on my machine and there is no code to do this. I can only imaging that the different JVM implementations handle this differently.

**Comment by BigAlanM** [comment] 2016-01-07 17:10
I was under the impression that Amidst checked to see if a history.txt file existed in the folder Amidst resides and if so it appends a line to the end of that file.  That's the way Skidoodle (Skiphs) described the behavior in his documentation. 
Just like Amidst checks for a "biome" folder and if it finds one saves a default.json file there.

I would love to see the text seed, if it exists, added to the history entry.

The fact that the save folder is remembered is probably a feature of Windows. It has worked that way for the last several Windows versions and now that you mention it all other programs I use remember their save folders. I have separate download folders for each of the different browsers I use.

The zoom thing isn't really a problem for me and I probably shouldn't have brought it up.
I normally don't run Amidst or AE in full screen. (I just tried Amidst4.0 in full screen on my 27" monitor --  WOW!  Even in Restricted mode that's more world than I will ever need to see at one time.

I have been using AmidstExporter.jar exclusively for quite some time and have become spoiled to the ability to change biome color files from a menu. (It's "Biome profile under "Options")

I'm not sure if I care about the Export function of AE. I've only used it once just to save time when I wanted to post the coordinates of structures of a world to a thread on the forums.  It doesn't seem to increase the size of the .jar but I have no idea what it would take to integrate the code into Amidst40.

My feelings are to remove Hell and Sky from the Highlight biomes menu list. They aren't displayed anyway so why display their colors?

**Comment by stefandollase** [comment] 2016-01-07 21:07
Ah, good that you describe the intended behavior. It seems, that I have missed it while I refactored the code. I will restore the old behavior for the history file.

BTW: The biome directory is now called biome-color-profiles, however, there is a command line parameter to specify the location of the directory, if you do not like the default.

Good, I will add the seed text to the history file.

I see that the "restore seed" functionality can be useful. However, it will not be a high priority.

I will look into the GUI of Amidst Exporter for changing biome color profiles, but (you already said it yourself) this will also not be a high priority.

To my knowledge, the export functionality was the original reason for @Treer to fork the project, so if we want to merge AmidstExporter back in completely this has to include the export functionality. However, I did not look into it to closely. It all seems to be implemented in one big class, so I guess it should not be too hard.

The Sky biome will actually be visible in the new version, since @Treer implemented a view for the end dimension, which also includes the end cities. So, I will rename Sky to The End, like Mojang did it in version 1.8. However, the Hell biome will be removed since it is never used.

**Comment by BigAlanM** [comment] 2016-01-08 03:22
I FORGOT ABOUT TREER's END MAP!!!!
DOOH!!!
Well, at this point, As the jumper said as he passed the sixth floor on his way down, "Looks good so far."

**Comment by stefandollase** [comment] 2016-01-09 01:44
I just created a beta3 release with lots of bug fixes. It also contains many of the changes from AmidstExporter. Most of the changes discussed in this issue are also included. Here is a list points that are still open:

* go back to a previous seed
* create a new world from the current seed but a different world type

Did I miss any more open points?

Also, I will not remove the hell biome for the following reasons:
  * there are even more confusing biomes in the list, that are not even listed in the wiki
  * a future minecraft update might add a functionality to generate a custom world where the overworld contains the hell biome.
  * renaming would just lead to inconsistence

Next, I guess I misunderstood you when you talked about AmidstExporters menu option ("Biome profile" under "Options"). Amidst has the same menu options, when you have the biome-color-profile directory. I expected something different than this :-P

**Comment by Treer** [comment] 2016-01-09 03:20
Regarding the export functionality, because it's specific to the [Ink and Parchment map system](http://buildingwithblocks.info), I have no issues with it being omitted from toolbox4minecraft-Amidst. Looking at how things are going, I may eventually end up replacing AmidstExporter with a fork of toolbox4minecraft-Amidst that has *only* the export functionality added.

**Comment by Treer** [comment] 2016-01-09 04:31
Actually... export functionality is useful for regression testing and quantifying tradeoffs such as that villager heuristic and likely end cities, so perhaps it should have some sort of export capability.

**Comment by BigAlanM** [comment] 2016-01-09 05:26
DAMN!!!!  I forgot that the Biome profile option only showed if it was useful!!!
My bad.

**Comment by BigAlanM** [comment] 2016-01-09 13:40
Question: Concerning 4.0b3
When viewing The End, should villages, mines, Strongholds, spawn point, Ocean Mounments, Desert Temples, and Witchhuts be displayed?
I did notice that clicking on one of the icons the location display will state that the structure is in the Overworld.
Does it matter? 
Is it possible to travel in The End and emerge in a different location in the Overworld?
Are distances equivalent between the two or is there a scaling difference like there is between the Nether and the Overworld?
This is just my ignorance showing.

**Comment by Treer** [comment] 2016-01-09 14:05
I fixed that user interface issue in AmidstExporter (today), presumably we'll do the same in this Amidst.

**Comment by BigAlanM** [comment] 2016-01-09 14:41
I downloaded AE142.jar and ran it within 20 minutes of it being uploaded.
Looks good.
I can live with either layer user interface (Amidst40 and/or AE142.
Ran AE142 with my 1.9 shapshot profile.  Igloo prediction and display works. Or, at least, displays structures that I'm aware of.
If anyone wishes to test this use the seed "-2788760844838102142". Spawn is at the border of a Cold Taiga and an Ice Plains with an Igloo with a basement in sight. Several more within 1k meters.

**Comment by BigAlanM** [comment] 2016-01-09 23:08
Re: history.txt 
I've just checked AE1.3.9, AE1.4.2, and Amidst4.0 
AE139 is still appending to the history.txt file in its folder.
Neither AE142 or Amidst40 is appending to their files.
Also neither AE142 or Amidst40 is seeing the biome folder like AE139 does.
CRAP!  I just closed AE139 and restarted it and now it doesn't work either!

**Comment by Treer** [comment] 2016-01-10 00:23
Perhaps the program you're using to view the history.txt file is preventing the next program to open the file from gaining write permissions?

**Comment by BigAlanM** [comment] 2016-01-10 02:45
Nope,  Notepad++ has a setting to monitor other files changing files it has open and to update its display as needed.  I can run AE and watch the history list update simultaneously and add a note to a history line if I see an interesting map.  I just have to make sure to hit Ctrl-S in Notepad++ to save the change or the next Amidst entry will overwrite my note.

**Comment by BigAlanM** [comment] 2016-01-10 23:36
I just noticed a behavior in AE that is lacking in Amidst4.0.
When I hit Ctrl-T in AE it brings up a file save dialog with a suggested file name already entered.
(screenshot<seed>.png)
If the name is acceptable all the user has to do is click on Save or modify the name and then click Save.
Amidst4.0 currently forces the user to type in a file name before hitting Save.
Also AE opens a Save dialog whereas Amidst4.0 opens an Open dialog and requires the user to click on "Open" to SAVE the screenshot.

**Comment by BigAlanM** [comment] 2016-01-11 08:17
I see why the icon for Amidst 4.0 looks so bad compared to the one in Amidst 3.7.
One's a 5kb file and the other is a 130kb file.

**Comment by BigAlanM** [comment] 2016-01-12 06:44
Why, when I click on a Overworld structure in 4.0b3 does the structure description say "{structure} in the Overworld [Xcoord,Zcoord]?
I understand why it desirable to display Nether fortress coordinates for both the Overworld and the Nether.
But why state the obvious.
Also, why display Overworld structures on THE END map?

**Comment by stefandollase** [comment] 2016-01-12 13:59
I am currently working on changes for the layer system. The menu will look similar to the screenshot posted by @Treer. I really like the solution. Also, I want to disable layers (including the menu item) that are not supported in the current minecraft version. This takes some more work, because I need to change how the Setting implementation and the menu implementation for this. Also, only the layers that belong to the current dimension will be displayed, nether fortresses are the exception to that rule. So, I will also remove the additional information about the dimension from most of the world icons again. It seemed like a good idea, however it is not for most of them :-P

I will also look into the other issues.

**Comment by stefandollase** [comment] 2016-01-13 15:18
@BigAlanM Regarding the two profiles that are displayed as "not found". This happens, when Amidst cannot find a valid version directory or a valid profile directory. A valid version directory is a version directory that contains both, the jar and the json file. A valid profile directory contains a saves directory. When no gameDir is set for the profile, the .minecraft directory is used as the profile directory instead.

It would be interesting to find the problem, so I can change the behavior described above. Maybe, you can have a look at the log messages? They should tell you whether it is the profile directory or the version directory that is invalid.

**Comment by stefandollase** [comment] 2016-01-13 15:27
Regarding the bad resolution of the icon: The only icon that I can find in the original AMIDST repository by @skiphs has a resolution of 32x32 pixel. If someone can provide the icon via a pull request with a better resolution, I can use this in the build process. However, please make sure that the icon does not contain asserts from mojang. Maybe @skiphs can provide the high resolution icon?

**Comment by stefandollase** [comment] 2016-01-13 16:11
I just created the new pre-release v4.0-beta4. It should fix all the bugs discussed in this issue, with the exception of my two posts above. It also has a greatly reworked layers menu.

As already stated in other places, I will not have that much time for Amidst for the next month. This is why I created feature request issues for all remaining tasks on my list. If someone wants to implement these features, just go ahead. When I get the time, I might also look into implementing them.

I will still look into this project regularly to respond to issues, fix bugs, merge pull requests and eventually create a stable release. However, I will not implement new features.

**Comment by BigAlanM** [comment] 2016-01-13 19:56
Re: the Amidst icon:  I just extracted the icon again just to make sure from Amidst3.7. The resulting file is 130kb.  MSPaint shows the resulting icon to be 256x256 pixels.

You were correct about not having created the save directories for the two beta versions. I had run the profiles to download the .jar and .json files but never ran them. I've now run both of them and created a world in each and now the profile selection dialog shows all profiles as found.  Thanks!

**Comment by stefandollase** [comment] 2016-01-13 20:17
Okay, since this actually causes problems, I will change Amidst to not require the saves directory in the profile directory. Thanks for reporting the problem.

**Comment by BigAlanM** [comment] 2016-01-13 20:55
I see that Amidst 4.0b4 hasn't incorporated the export functionality of AE.
As I said earlier, I haven't used that much but it is a useful feature.

**Comment by BigAlanM** [comment] 2016-01-14 13:19
I'd like to see the layers check list stay open until it loses focus rather than having it close every time an  option is toggled.  I realize that if I were to learn the hot keys this wouldn't be a problem but I've yet to print out a screen capture of the menu.

**Comment by stefandollase** [comment] 2016-01-14 17:11
@BigAlanM I do understand your request about the layers menu. However, I am not sure whether the GUI framework we use supports it. To me, this is not a bug, but a feature request, so I will not be able to look into it in the near future. Can you create a feature request issue for it, so it is more visible? Thanks.

**Comment by stefandollase** [comment] 2016-01-14 18:35
This issue becomes pretty messy and confusing. I often have to go back and check that I handled all of the points that were discussed. Thus I am closing it. Please create separate issues for new bugs, feature requests, ...

If I did not miss anything, I fixed all bugs discussed in this issue up to this point. Also, for all other open points there should be separate issues.

**Closed by stefandollase** 2016-01-14 18:35 UTC
