### ISSUE TITLE
New From Random Seed (With Filters)

### ISSUE THREAD

**Issue by andrbrow** [toolbox4minecraft/amidst#831] opened 2020-07-30 01:51 UTC
First off - Absolutely amazing program!  I've used it for years and have just introduced my kids to it (as well as many people via Reddit).  

For those of us that spend countless hours combing random seeds for the perfect survival or server seed, I believe a list of filters that would help narrow in our search a bit.  

Examples that I could have used in the past:
Seeds with village within X blocks from spawn
Seeds with Outpost within X blocks of Stronghold AND Fortress
Seeds with Spawn in Jungle Biome
Seeds with Warm ocean biome within X blocks of spawn (survival island?)
Seeds numbers that range from 0 to 2147483648 (for finding seeds for bedrock (this isn't perfect but pretty close))
Or any combination of these options

I looked to see if this was asked before and didn't find anything, so apolgies if it's been asked before.  I just think it would help me and probably others out a whole lot.

Again, amazing work on this program! wouldn't dream of starting a survival world without it!

**Comment by moulins** [comment] 2020-08-06 15:33
Duplicate of #120.

This is a long-requested feature however, and implementation work never got to a finished state, so don't expect it to be added soon.

**Closed by moulins** 2020-08-06 15:33 UTC
