### ISSUE TITLE
Can't open seed on amidst

### ISSUE THREAD

**Issue by Onamayte** [toolbox4minecraft/amidst#611] opened 2019-12-28 19:29 UTC
Hello, I have a problem with opening a seed on amidst. https://pastebin.com/YPamLLpb

**Comment by HTMLSniper** [comment] 2019-12-30 00:27
Same here https://pastebin.com/v4YB6Pf5

**Comment by moulins** [comment] 2020-01-03 17:05
Duplicate of #538; this is fixed in the latest release (v4.4-beta1).

**Closed by moulins** 2020-01-03 17:05 UTC
