### ISSUE TITLE
Will amidst work for 1.14? (or snapshots)

### ISSUE THREAD

**Issue by dojofemy** [toolbox4minecraft/amidst#476] opened 2019-03-07 01:40 UTC
Hi
I use amidst a lot to navigate through my minecraft worlds... now that I have gathered a bunch of people for a multiplayer server, we want to reset our world when 1.14 comes out - and we want to find a good seed :) right now I can't because it doesn't work with the 1.14 snapshots - is there a way to fix this issue, I really want it working when 1.14 comes out! or at least just for the snapshots since most of the world generation already has been implemented, such as new villages, pillager towers, bamboo forests, berry bushes etc.

let me know if there is a fix for this 👍 
-femy

**Comment by moulins** [comment] 2019-03-07 17:41
Closing as duplicate of #460.

**Closed by moulins** 2019-03-07 17:41 UTC
