### ISSUE TITLE
amidst crashes on latest snapshots - Minecraft Java, MacOS

### ISSUE THREAD

**Issue by zslg01** [toolbox4minecraft/amidst#962] opened 2021-05-15 17:51 UTC
amidst crashes on latest snapshots to Minecraft 1.16+ or 1.17

[info] Amidst v4.6
[info] Current system time: 2021-05-15 13:48:20.197
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.16'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '15.0.1'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: '/Users/sysadmin/Library/Application Support/minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] Successfully loaded profile list.
[info] using minecraft launcher profile 'Latest snapshot' with versionId '21w19a'
[info] Loading libraries.
[info] Found library com.mojang:blocklist:1.0.5 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
[info] Found library com.mojang:patchy:2.0.5 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/patchy/2.0.5/patchy-2.0.5.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j:66.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
[info] Found library com.mojang:javabridge:1.1.23 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.18 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
[info] Found library com.mojang:datafixerupper:4.0.26 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:2.1.29 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/authlib/2.1.29/authlib-2.1.29.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library org.lwjgl:lwjgl:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.2
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.2
[info] Found library org.lwjgl:lwjgl-openal:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.2
[info] Found library org.lwjgl:lwjgl-opengl:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.2
[info] Found library org.lwjgl:lwjgl-glfw:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.2
[info] Found library org.lwjgl:lwjgl-stb:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.2
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.2
[info] Found library org.lwjgl:lwjgl:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.2
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.2
[info] Found library org.lwjgl:lwjgl-openal:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.2
[info] Found library org.lwjgl:lwjgl-opengl:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.2
[info] Found library org.lwjgl:lwjgl-glfw:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.2
[info] Found library org.lwjgl:lwjgl-stb:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.2
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.1 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.2
[info] Found library com.mojang:text2speech:1.11.3 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
[info] Found library ca.weblite:java-objc-bridge:1.0.0 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
[info] Found library ca.weblite:java-objc-bridge:1.0.0 at file:/Users/sysadmin/Library/Application%20Support/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
[info] Finished loading libraries.
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-0,1,main]
[crash] java.lang.UnsupportedClassVersionError: net/minecraft/server/MinecraftServer has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 59.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:514)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:422)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:416)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:415)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:269)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:260)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:255)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:33)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:22)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:142)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by moulins** [comment] 2021-05-16 17:57
Duplicate of #963; this will be fixed in the next release.

**Closed by moulins** 2021-05-16 17:57 UTC
