### ISSUE TITLE
Can't retrieve BiomeDataOracle for dimension Nether

### ISSUE THREAD

**Issue by Shroototem** [toolbox4minecraft/amidst#950] opened 2021-03-30 19:43 UTC
Crash with Amidst v4.6 and Minecraft 1.12.2.

```
[info] Amidst v4.6
[info] Current system time: 2021-03-30 15:39:43.909
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_281'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: 'C:\Users\xxxio\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile '' with versionId '1.12.2'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:librarylwjglopenal:20100824 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.9.Final at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library com.mojang:realms:1.10.22 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:7.1.0 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[info] Found library org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library net.java.jinput:jinput-platform:2.0.5 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/C:/Users/xxxio/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Recognised Minecraft Version 1.12.2 with the magic string "ulrlozmtry[Loo;pl[J[[Jph".
[info] Reading 1.12.2.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class IntCache: bdo
[info] Found class ChunkProviderSettingsFactory: ayx$a
[info] Found class WorldType: amz
[info] Found class BlockInit: ni
[info] Found class GenLayer: bdq
[info] Found class ChunkProviderSettings: ayx
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class method bdq.a(long, @WorldType) -> GenLayer.initializeAllBiomeGenerators2
[info] unable to find the real class method bdq.a(long, @WorldType, String) -> GenLayer.initializeAllBiomeGenerators3
[info] Classes loaded.
[info] Minecraft load complete.
[info] Supported dimensions for world configuration: Overworld
[info] Not writing to seed history file, because it does not exist: history.txt
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.RuntimeException: Can't retrieve BiomeDataOracle for dimension Nether
	at amidst.mojangapi.world.versionfeatures.DefaultVersionFeatures.getBiomeOracle(DefaultVersionFeatures.java:810)
	at amidst.mojangapi.world.versionfeatures.DefaultVersionFeatures.lambda$scatteredFeature$32(DefaultVersionFeatures.java:827)
	at amidst.mojangapi.world.versionfeatures.VersionFeature.lambda$fixed$1(VersionFeature.java:25)
	at amidst.mojangapi.world.versionfeatures.VersionFeatures$Entry.getOrCompute(VersionFeatures.java:119)
	at amidst.mojangapi.world.versionfeatures.VersionFeatures.get(VersionFeatures.java:29)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:138)
	at amidst.mojangapi.world.WorldBuilder.from(WorldBuilder.java:51)
	at amidst.mojangapi.RunningLauncherProfile.createWorld(RunningLauncherProfile.java:69)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:73)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:93)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:78)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:138)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by moulins** [comment] 2021-05-14 16:23
I can't reproduce on the development version, so I'll close this.

If the bug still occurs when the next Amidst version is release, fell free to open a new issue!

**Closed by moulins** 2021-05-14 16:23 UTC
