### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by LovesAsuna** [toolbox4minecraft/amidst#525] opened 2019-08-15 06:15 UTC
I use multimc,but amdist can't detect my .minecraft folder

**Comment by Shadowhenge** [comment] 2019-08-23 20:51
I have the same issue, but not using anything other than the the default launcher.  It wont detect it and theres no option to tell it where it is.

**Comment by OronDF343** [comment] 2019-08-31 18:01
+1. I use exclusively MultiMC, would be nice to have a config file or command-line option for this.

**Comment by moulins** [comment] 2019-10-10 19:04
Duplicate of #126.

**Closed by moulins** 2019-10-10 19:04 UTC
