### ISSUE TITLE
Not working on java 1.16

### ISSUE THREAD

**Issue by Thenaikan** [toolbox4minecraft/amidst#775] opened 2020-06-23 18:40 UTC
Updated to 1.16 today and map fails to load. See attached for errors.
![java-116-error](https://user-images.githubusercontent.com/67339081/85443583-0fcb8600-b557-11ea-9e01-c7d25aee9ad4.jpg)
 to load

**Comment by moulins** [comment] 2020-06-23 21:52
Duplicate of #719; Minecraft 1.16 isn't supported yet. (Support should come in the next days if all goes well)

**Closed by moulins** 2020-06-23 21:52 UTC
