### ISSUE TITLE
Amidst crashes when loading savegame 1.16.1

### ISSUE THREAD

**Issue by dorianpb** [toolbox4minecraft/amidst#816] opened 2020-07-15 17:26 UTC
[info] Amidst v4.5-beta1
[info] Current system time: 2020-07-15 13:23:36.202
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '5.7.8-xanmod2-2-xanmod'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '13.0.3'
[info] System.getProperty("java.vendor") == 'Azul Systems, Inc.'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: '/home/dorianpb/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] There are no updates available.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'Latest version' with versionId '1.16.1'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/home/dorianpb/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/home/dorianpb/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/dorianpb/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/dorianpb/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j:66.1 at file:/home/dorianpb/.minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
[info] Found library com.mojang:javabridge:1.0.22 at file:/home/dorianpb/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/dorianpb/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/dorianpb/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/dorianpb/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/dorianpb/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/dorianpb/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/dorianpb/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/dorianpb/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/dorianpb/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.17 at file:/home/dorianpb/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[info] Found library com.mojang:datafixerupper:3.0.25 at file:/home/dorianpb/.minecraft/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/dorianpb/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.6.25 at file:/home/dorianpb/.minecraft/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/dorianpb/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/dorianpb/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/dorianpb/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/dorianpb/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/home/dorianpb/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/dorianpb/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/dorianpb/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/dorianpb/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/home/dorianpb/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/home/dorianpb/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Recognised Minecraft Version 1.16 with the magic string "bqedae$adaianoamczutlgm$aabp[Jablaaruxczyvauuadsuwcva".
[info] Reading 1.16.1.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class OverworldBiomeZoomer: btf
[info] Found class WorldGenSettings: cix
[info] Found class Util: v
[info] Found class Biome: bre
[info] Found class Registry: gl
[info] Found class ResourceKey: ug
[info] Found class NoiseBiomeProvider: brg$a
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class constructor ug.<init>(java.lang.String) -> ResourceKey.<init>
[info] Classes loaded.
[info] Minecraft load complete.
[info] Creating world with seed '7451095230088863711' and type 'Default'
[info] Using the following generator options: 
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NoSuchMethodError: 'void com.google.gson.Gson.<init>(com.google.gson.internal.Excluder, com.google.gson.FieldNamingStrategy, java.util.Map, boolean, boolean, boolean, boolean, boolean, boolean, boolean, com.google.gson.LongSerializationPolicy, java.util.List)'
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:569)
	at adt.<clinit>(SourceFile:27)
	at o.a(SourceFile:61)
	at u.a(SourceFile:137)
	at aep.b(SourceFile:204)
	at aep.<clinit>(SourceFile:201)
	at v.b(SourceFile:199)
	at v.a(SourceFile:192)
	at aoq$a.a(SourceFile:631)
	at aoq.a(SourceFile:146)
	at aoq.<clinit>(SourceFile:152)
	at gl.S(SourceFile:171)
	at gl.a(SourceFile:220)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at gl.<clinit>(SourceFile:219)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1045)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at amidst.clazz.symbolic.SymbolicField.get(SymbolicField.java:45)
	at amidst.clazz.symbolic.SymbolicField.getValueFromObject(SymbolicField.java:36)
	at amidst.clazz.symbolic.SymbolicField.getStaticValue(SymbolicField.java:32)
	at amidst.clazz.symbolic.SymbolicClass.getStaticFieldValue(SymbolicClass.java:103)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.initializeIfNeeded(LocalMinecraftInterface.java:151)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:65)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.createWorld(LoggingMinecraftInterface.java:20)
	at amidst.mojangapi.world.WorldBuilder.initInterfaceAndGetFeatures(WorldBuilder.java:78)
	at amidst.mojangapi.world.WorldBuilder.fromSaveGame(WorldBuilder.java:63)
	at amidst.mojangapi.RunningLauncherProfile.createWorldFromSaveGame(RunningLauncherProfile.java:74)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:78)
	at amidst.gui.main.Actions.openSaveGame(Actions.java:107)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:138)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by moulins** [comment] 2020-07-18 10:16
This bug is fixed on the latest release (v4.5-beta3); closing as duplicate of #797.

**Closed by moulins** 2020-07-18 10:16 UTC
Labels: duplicate
