### ISSUE TITLE
Amidst needs an option to output structure coords to txt file.

### ISSUE THREAD

**Issue by Footsiefat** [toolbox4minecraft/amidst#515] opened 2019-07-22 00:57 UTC
I need it so I can, for example, go to the end and select output(end citys) and it will output something like this to the selected txt file:
End city xxxx xxxx
Possible end city xxxx xxxx
etc...

This feature should also have an option where to start its search and how far from the starting coords it should search from.

Many thanks,
Footsiefat.

**Comment by moulins** [comment] 2019-07-22 22:30
Closing as duplicate of #494.

**Closed by moulins** 2019-07-22 22:30 UTC
