### ISSUE TITLE
Amidst can't find any of my profiles.

### ISSUE THREAD

**Issue by KarlGriffinsteed** [toolbox4minecraft/amidst#503] opened 2019-06-28 18:36 UTC
I have the most recent version downloaded, but when I run it, it says "Not Found" by most of my profiles . . . including the vanilla/unmodded ones! Editing the profiles that do work seem to make them "Unfindable". What's causing the problem? How do I fix this?
![UT13](https://user-images.githubusercontent.com/52331066/60363581-8fa52b80-99a9-11e9-8c07-ebb9d94c1afc.png)

**Comment by WhiteHoodHacker** [comment] 2019-06-29 06:58
Having the same issue too. I believe the new Minecraft launcher update might have changed how profiles are handled.

**Comment by highlander1599** [comment] 2019-06-29 15:51
Me too

**Comment by moulins** [comment] 2019-06-29 20:12
Duplicate of #503, which will be fixed in the next version.

To have the profile working in Amidst, you need to select a specific version, and not "latest release" or "latest snapshot".

**Closed by moulins** 2019-06-29 20:12 UTC
