### ISSUE TITLE
Allow for searching of specific biome

### ISSUE THREAD

**Issue by PressXFor** [toolbox4minecraft/amidst#738] opened 2020-04-15 13:10 UTC
I downloaded this mod hoping I could find the origin biome in biomes o' plenty. After scrolling through 500,000 blocks in each direction, I gave up. I wish there was a search bar function that would allow me to type the name of the biome in and get a list of coordinates for the matching biomes. #

**Comment by moulins** [comment] 2020-04-16 13:15
Duplicate of #120.

Doesn't Biome O' Plenty has a command to quickly locate biomes? A quick google search gave me [this link](https://biomesoplenty.fandom.com/wiki/Commands).

**Closed by moulins** 2020-04-16 13:15 UTC
