### ISSUE TITLE
make email and web links clickable from the about pop up

### ISSUE THREAD

**Issue by BlueSteelAUS** [toolbox4minecraft/amidst#109] opened 2016-03-01 07:28 UTC
make email and web links clickable from the about pop up

**Comment by BigAlanM** [comment] 2016-03-01 11:57
This is a duplicate of #95

**Comment by stefandollase** [comment] 2016-03-01 12:42
Thanks, this would be nice, indeed. However, I close this to keep further discussion about it in #95.

**Closed by stefandollase** 2016-03-01 12:42 UTC
Labels: duplicate, feature request
