### ISSUE TITLE
find dungeons 

### ISSUE THREAD

**Issue by thistastesugly** [toolbox4minecraft/amidst#941] opened 2021-02-06 20:36 UTC
can you add a feature where it shows a dungeons coordinates

**Comment by moulins** [comment] 2021-02-11 16:04
Duplicate of #57.

This will probably never be implemented, because accurate dungeon prediction requires generating the actual content of each chunk, which would be prohibitively expensive without huge optimizations efforts.

**Closed by moulins** 2021-02-11 16:04 UTC
