### ISSUE TITLE
Amidst can't run with custom non-Mojang launchers

### ISSUE THREAD

**Issue by TheThunderGuyS** [toolbox4minecraft/amidst#761] opened 2020-05-17 20:28 UTC
I primarily use [MultiMC](https://github.com/MultiMC/MultiMC5) to play Minecraft which does not save to `.minecraft` however because of this I can't start Amidst. It brings up an error of not being able to find `.minecraft` (which obviously doesn't exist). I don't know which files within there it needs but copying my saves and version JAR/JSON didn't work. 

It most likely needs the files for instances but it would be nice if you could set up "custom" instances within Amidst using the path to a JAR and save directory. Otherwise I have to install Mojang's launcher just to use Amidst, which I don't want to have to do. I would really appreciate if this could be addressed.

**Comment by moulins** [comment] 2020-05-17 21:28
Closing as duplicate of #126.

-----

You can start "custom instances" from the command-line (see [here](https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface)), by specifying the `-mcjar` and `-mcjson` arguments. I've never tested it with MultiMC, but it should work as long as you have a vanilla Minecraft JAR.

**Closed by moulins** 2020-05-17 21:28 UTC
Labels: duplicate

**Comment by cbyrne** [comment] 2020-05-21 14:52
> You can start "custom instances" from the command-line (see here), by specifying the -mcjar and -mcjson arguments. I've never tested it with MultiMC, but it should work as long as you have a vanilla Minecraft JAR.

This doesn't work for me
![image](https://user-images.githubusercontent.com/31479541/82571579-11321900-9b7b-11ea-9304-11a5b8087cb4.png)

**Comment by moulins** [comment] 2020-05-21 19:56
Oh, yeah, my bad; you also need to use the `-mcpath` option to specify the location of the `MultiMC` directory.  
You'll have to add some dummy files at the root of the folder for Amidst to recognize it as a valid Minecraft directory:
 - an empty `saves` folder
 - an empty `versions` folder,
 - an empty `launcher_profiles.json` file.

**Comment by alexis-evelyn** [comment] 2020-06-19 06:30
What do you mean the MultiMC directory?

I currently have my setup as `java -jar amidst-v4-4.jar -mcpath /Users/alexis/Applications/MultiMC.app/Contents/MacOS/instances/1.16/ -mcjar /Users/alexis/Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.16-rc1/minecraft-1.16-rc1-client.jar -mcjson /Users/alexis/Applications/MultiMC.app/Contents/MacOS/meta/net.minecraft/1.16-rc1.json`.

I've also tried `/Users/alexis/Applications/MultiMC.app/Contents/MacOS/instances/` and `/Users/alexis/Applications/MultiMC.app/Contents/MacOS/instances/1.16/.minecraft/` for the mcpath and I keep getting the error `invalid '.minecraft' directory at: <one of the directories I've tried>.

**Comment by moulins** [comment] 2020-06-23 21:47
I'm talking about the `<MultiMC root>` directory mentionned [here](https://github.com/MultiMC/MultiMC5/wiki/Directory-Structure). In your case, it should probably bz `/Users/alexis/Applications/MultiMC.app/Contents/MacOS/`.
