### ISSUE TITLE
How to randomly generate 32 bit seed?

### ISSUE THREAD

**Issue by W0lfgangster** [toolbox4minecraft/amidst#552] opened 2019-10-15 03:51 UTC
I'm working on a seed testing tool that uses this API but WorldSeed.random() generates 64 bit seeds and windows 10 edition only works with 32 bit seeds (stupid) is there a way to translate an integer to the WorldSeed Class?

**Comment by moulins** [comment] 2019-10-15 09:56
Duplicate of #463 and #27.

**Closed by moulins** 2019-10-15 09:56 UTC
