### ISSUE TITLE
Rapidly export .png previews

### ISSUE THREAD

**Issue by VeryGoodDog** [toolbox4minecraft/amidst#469] opened 2019-01-13 21:08 UTC
In order to find a seed for a world that met specific requirements. I tried to hack the app itself but there were too many layers of calls before you actually render the map.

Having the app export a preview of the map, X by Y, with the same features of the live view, i.e. biome highlights, structures, spawn.
Having it also generate 50 at once would be nice, too.

**Comment by moulins** [comment] 2019-02-17 19:34
Closing as duplicate of #232.

For your use case, you can export an PNG image with `World > Take a screenshot`, which should be automatable (Someone already made a searcher based on this: https://github.com/azuntik/Amidst-Seed-Hunter).

There are also other tools devoted to seed search:  
  - https://github.com/Cubitect/cubiomes, written in C
  - My experimental fork of Amidst, https://github.com/moulins/amidst/tree/seed-filter

**Closed by moulins** 2019-02-17 19:34 UTC
