### ISSUE TITLE
Aimdst v4.5-beta1 [W10 - Minecraft 1.16.1] (BUG)

### ISSUE THREAD

**Issue by Unamunoqueva** [toolbox4minecraft/amidst#795] opened 2020-07-01 08:53 UTC
the used operating system and version: Microsoft Windows 10 Pro  10.0.18363 N/D Compilación 18363
the used Java version: Java 8 update 251 (compilacion 1.8.0_251-b08)
the used Minecraft version: Minecraft 1.16.1
the used Amidst version: amidst-v4-5-beta1
What did you do to produce the error? Try to load level.dat
(How) can the error be reproduced? Try to load level.dat
What did you expect to happen? Load my world from level.dat
What did actually happen? Not load the world
the error message, if any:

[warning] java.io.IOException: [JNBT] Invalid tag type: 12.
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:208)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:96)
	at amidst.mojangapi.file.nbt.NBTUtils.readTagFromFile(NBTUtils.java:22)
	at amidst.mojangapi.file.nbt.LevelDatNbt.from(LevelDatNbt.java:17)
	at amidst.mojangapi.file.service.SaveDirectoryService.readLevelDat(SaveDirectoryService.java:71)
	at amidst.mojangapi.file.MinecraftInstallation.newSaveGame(MinecraftInstallation.java:95)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:78)
	at amidst.gui.main.Actions.openSaveGame(Actions.java:107)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:138)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by reynaldo666** [comment] 2020-07-01 11:14
Same in Ubuntu 16.04 64 bits. Any workaround, please?

**Comment by moulins** [comment] 2020-07-01 11:51
Duplicate of #777; this will be fixed in the next release.

As a workaround, you can still enter the world seed manually (with `ctrl+N`)

**Closed by moulins** 2020-07-01 11:51 UTC

**Comment by reynaldo666** [comment] 2020-07-07 13:33
> Duplicate of #777; this will be fixed in the next release.
> 
> As a workaround, you can still enter the world seed manually (with `ctrl+N`)

When we will have another release, Sir?

**Comment by moulins** [comment] 2020-07-14 22:13
Amidst v4.6-beta3 is already out, and fixes this issue.
