### ISSUE TITLE
MultiMC support

### ISSUE THREAD

**Issue by forkiesassds** [toolbox4minecraft/amidst#919] opened 2020-12-02 12:38 UTC
I use a 3rd party Minecraft launcher (MultiMC) which does not use the typical structure the Minecraft launcher uses, instead of profiles MultiMC uses instances, all versions are stored in a central folder (`libraries\com\mojang\minecraft`), and libraries are stored at the central libraries folder (`libraries`), and it does not use launcher_profiles.json

**Comment by moulins** [comment] 2020-12-06 02:14
Duplicate of #126.

Amidst doesn't support custom launchers, exactly for the reasons you gave: the folder structure isn't the same as the official Launcher.

**Closed by moulins** 2020-12-06 02:14 UTC
