### ISSUE TITLE
Amidst crashes directly on startup

### ISSUE THREAD

**Issue by MillsHimself** [toolbox4minecraft/amidst#539] opened 2019-10-03 02:14 UTC
Hi,
Like the title says, amidst crashes right after I run the program. No profile selection, nothing, just immediately crashes. The bug occurs with the .exe and the .jar.
My Minecraft is in C:/ProgramData/.minecraft (tried to run amidst with the -mcpath option, didn't worked) and I have no mod installed (not even optifine)

OS: Windows 10, 64 bits
Java: 1.8.0_221
Amidst: 4.3

`[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: java.io.IOException: Stream closed
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:50)
	at amidst.Amidst.createMetadata(Amidst.java:61)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.util.Properties$LineReader.readLine(Unknown Source)
	at java.util.Properties.load0(Unknown Source)
	at java.util.Properties.load(Unknown Source)
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:45)
	... 3 more
`

**Comment by moulins** [comment] 2019-10-10 21:48
Duplicate of #389.

**Closed by moulins** 2019-10-10 21:48 UTC
Labels: duplicate
